// Code generated by internal/cmd/schemagen. DO NOT EDIT.
//
// Source: internal/schemas, generated from codex-cli 0.149.0.
// Regenerate with `make generate`.

package protocol

type AddCreditsNudgeCreditType string

const (
	AddCreditsNudgeCreditTypeCredits    AddCreditsNudgeCreditType = "credits"
	AddCreditsNudgeCreditTypeUsageLimit AddCreditsNudgeCreditType = "usage_limit"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v AddCreditsNudgeCreditType) IsKnown() bool {
	switch v {
	case AddCreditsNudgeCreditTypeCredits,
		AddCreditsNudgeCreditTypeUsageLimit:
		return true
	}
	return false
}

// String returns the wire value.
func (v AddCreditsNudgeCreditType) String() string { return string(v) }

type AddCreditsNudgeEmailStatus string

const (
	AddCreditsNudgeEmailStatusSent           AddCreditsNudgeEmailStatus = "sent"
	AddCreditsNudgeEmailStatusCooldownActive AddCreditsNudgeEmailStatus = "cooldown_active"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v AddCreditsNudgeEmailStatus) IsKnown() bool {
	switch v {
	case AddCreditsNudgeEmailStatusSent,
		AddCreditsNudgeEmailStatusCooldownActive:
		return true
	}
	return false
}

// String returns the wire value.
func (v AddCreditsNudgeEmailStatus) String() string { return string(v) }

type AdditionalContextKind string

const (
	AdditionalContextKindUntrusted   AdditionalContextKind = "untrusted"
	AdditionalContextKindApplication AdditionalContextKind = "application"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v AdditionalContextKind) IsKnown() bool {
	switch v {
	case AdditionalContextKindUntrusted,
		AdditionalContextKindApplication:
		return true
	}
	return false
}

// String returns the wire value.
func (v AdditionalContextKind) String() string { return string(v) }

type AgentMessageDelivery string

const (
	AgentMessageDeliveryAsync AgentMessageDelivery = "async"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v AgentMessageDelivery) IsKnown() bool {
	switch v {
	case AgentMessageDeliveryAsync:
		return true
	}
	return false
}

// String returns the wire value.
func (v AgentMessageDelivery) String() string { return string(v) }

type AppTemplateUnavailableReason string

const (
	AppTemplateUnavailableReasonNotConfiguredForWorkspace AppTemplateUnavailableReason = "NOT_CONFIGURED_FOR_WORKSPACE"
	AppTemplateUnavailableReasonNoActiveWorkspace         AppTemplateUnavailableReason = "NO_ACTIVE_WORKSPACE"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v AppTemplateUnavailableReason) IsKnown() bool {
	switch v {
	case AppTemplateUnavailableReasonNotConfiguredForWorkspace,
		AppTemplateUnavailableReasonNoActiveWorkspace:
		return true
	}
	return false
}

// String returns the wire value.
func (v AppTemplateUnavailableReason) String() string { return string(v) }

type AppToolApproval string

const (
	AppToolApprovalAuto    AppToolApproval = "auto"
	AppToolApprovalPrompt  AppToolApproval = "prompt"
	AppToolApprovalWrites  AppToolApproval = "writes"
	AppToolApprovalApprove AppToolApproval = "approve"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v AppToolApproval) IsKnown() bool {
	switch v {
	case AppToolApprovalAuto,
		AppToolApprovalPrompt,
		AppToolApprovalWrites,
		AppToolApprovalApprove:
		return true
	}
	return false
}

// String returns the wire value.
func (v AppToolApproval) String() string { return string(v) }

// Configures who approval requests are routed to for review. Examples include sandbox escapes, blocked network access, MCP approval prompts, and ARC escalations. Defaults to `user`. `auto_review` uses a carefully prompted subagent to gather relevant context and apply a risk-based decision framework before approving or denying the request. The legacy value `guardian_subagent` is accepted for compatibility.
type ApprovalsReviewer string

const (
	ApprovalsReviewerUser             ApprovalsReviewer = "user"
	ApprovalsReviewerAutoReview       ApprovalsReviewer = "auto_review"
	ApprovalsReviewerGuardianSubagent ApprovalsReviewer = "guardian_subagent"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ApprovalsReviewer) IsKnown() bool {
	switch v {
	case ApprovalsReviewerUser,
		ApprovalsReviewerAutoReview,
		ApprovalsReviewerGuardianSubagent:
		return true
	}
	return false
}

// String returns the wire value.
func (v ApprovalsReviewer) String() string { return string(v) }

// [UNSTABLE] Source that produced a terminal approval auto-review decision.
type AutoReviewDecisionSource string

const (
	AutoReviewDecisionSourceAgent AutoReviewDecisionSource = "agent"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v AutoReviewDecisionSource) IsKnown() bool {
	switch v {
	case AutoReviewDecisionSourceAgent:
		return true
	}
	return false
}

// String returns the wire value.
func (v AutoReviewDecisionSource) String() string { return string(v) }

// EXPERIMENTAL: requires WithExperimentalAPI(). The server rejects this
// unless capabilities.experimentalApi was set during initialize.
type AwsCredentialType string

const (
	AwsCredentialTypeAccessKeys    AwsCredentialType = "accessKeys"
	AwsCredentialTypeBedrockAPIKey AwsCredentialType = "bedrockApiKey"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v AwsCredentialType) IsKnown() bool {
	switch v {
	case AwsCredentialTypeAccessKeys,
		AwsCredentialTypeBedrockAPIKey:
		return true
	}
	return false
}

// String returns the wire value.
func (v AwsCredentialType) String() string { return string(v) }

type CancelLoginAccountStatus string

const (
	CancelLoginAccountStatusCanceled CancelLoginAccountStatus = "canceled"
	CancelLoginAccountStatusNotFound CancelLoginAccountStatus = "notFound"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v CancelLoginAccountStatus) IsKnown() bool {
	switch v {
	case CancelLoginAccountStatusCanceled,
		CancelLoginAccountStatusNotFound:
		return true
	}
	return false
}

// String returns the wire value.
func (v CancelLoginAccountStatus) String() string { return string(v) }

type CLIAuthCredentialsStoreMode string

const (
	CLIAuthCredentialsStoreModeFile      CLIAuthCredentialsStoreMode = "file"
	CLIAuthCredentialsStoreModeKeyring   CLIAuthCredentialsStoreMode = "keyring"
	CLIAuthCredentialsStoreModeAuto      CLIAuthCredentialsStoreMode = "auto"
	CLIAuthCredentialsStoreModeEphemeral CLIAuthCredentialsStoreMode = "ephemeral"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v CLIAuthCredentialsStoreMode) IsKnown() bool {
	switch v {
	case CLIAuthCredentialsStoreModeFile,
		CLIAuthCredentialsStoreModeKeyring,
		CLIAuthCredentialsStoreModeAuto,
		CLIAuthCredentialsStoreModeEphemeral:
		return true
	}
	return false
}

// String returns the wire value.
func (v CLIAuthCredentialsStoreMode) String() string { return string(v) }

type CodexResponseHandoffMode string

const (
	CodexResponseHandoffModeThinking   CodexResponseHandoffMode = "thinking"
	CodexResponseHandoffModeCommentary CodexResponseHandoffMode = "commentary"
	CodexResponseHandoffModeBemTags    CodexResponseHandoffMode = "bemTags"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v CodexResponseHandoffMode) IsKnown() bool {
	switch v {
	case CodexResponseHandoffModeThinking,
		CodexResponseHandoffModeCommentary,
		CodexResponseHandoffModeBemTags:
		return true
	}
	return false
}

// String returns the wire value.
func (v CodexResponseHandoffMode) String() string { return string(v) }

type CollabAgentStatus string

const (
	CollabAgentStatusPendingInit CollabAgentStatus = "pendingInit"
	CollabAgentStatusRunning     CollabAgentStatus = "running"
	CollabAgentStatusInterrupted CollabAgentStatus = "interrupted"
	CollabAgentStatusCompleted   CollabAgentStatus = "completed"
	CollabAgentStatusErrored     CollabAgentStatus = "errored"
	CollabAgentStatusShutdown    CollabAgentStatus = "shutdown"
	CollabAgentStatusNotFound    CollabAgentStatus = "notFound"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v CollabAgentStatus) IsKnown() bool {
	switch v {
	case CollabAgentStatusPendingInit,
		CollabAgentStatusRunning,
		CollabAgentStatusInterrupted,
		CollabAgentStatusCompleted,
		CollabAgentStatusErrored,
		CollabAgentStatusShutdown,
		CollabAgentStatusNotFound:
		return true
	}
	return false
}

// String returns the wire value.
func (v CollabAgentStatus) String() string { return string(v) }

type CollabAgentTool string

const (
	CollabAgentToolSpawnAgent  CollabAgentTool = "spawnAgent"
	CollabAgentToolSendInput   CollabAgentTool = "sendInput"
	CollabAgentToolResumeAgent CollabAgentTool = "resumeAgent"
	CollabAgentToolWait        CollabAgentTool = "wait"
	CollabAgentToolCloseAgent  CollabAgentTool = "closeAgent"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v CollabAgentTool) IsKnown() bool {
	switch v {
	case CollabAgentToolSpawnAgent,
		CollabAgentToolSendInput,
		CollabAgentToolResumeAgent,
		CollabAgentToolWait,
		CollabAgentToolCloseAgent:
		return true
	}
	return false
}

// String returns the wire value.
func (v CollabAgentTool) String() string { return string(v) }

type CollabAgentToolCallStatus string

const (
	CollabAgentToolCallStatusInProgress CollabAgentToolCallStatus = "inProgress"
	CollabAgentToolCallStatusCompleted  CollabAgentToolCallStatus = "completed"
	CollabAgentToolCallStatusFailed     CollabAgentToolCallStatus = "failed"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v CollabAgentToolCallStatus) IsKnown() bool {
	switch v {
	case CollabAgentToolCallStatusInProgress,
		CollabAgentToolCallStatusCompleted,
		CollabAgentToolCallStatusFailed:
		return true
	}
	return false
}

// String returns the wire value.
func (v CollabAgentToolCallStatus) String() string { return string(v) }

type CommandExecutionSource string

const (
	CommandExecutionSourceAgent                  CommandExecutionSource = "agent"
	CommandExecutionSourceUserShell              CommandExecutionSource = "userShell"
	CommandExecutionSourceUnifiedExecStartup     CommandExecutionSource = "unifiedExecStartup"
	CommandExecutionSourceUnifiedExecInteraction CommandExecutionSource = "unifiedExecInteraction"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v CommandExecutionSource) IsKnown() bool {
	switch v {
	case CommandExecutionSourceAgent,
		CommandExecutionSourceUserShell,
		CommandExecutionSourceUnifiedExecStartup,
		CommandExecutionSourceUnifiedExecInteraction:
		return true
	}
	return false
}

// String returns the wire value.
func (v CommandExecutionSource) String() string { return string(v) }

type CommandExecutionStatus string

const (
	CommandExecutionStatusInProgress CommandExecutionStatus = "inProgress"
	CommandExecutionStatusCompleted  CommandExecutionStatus = "completed"
	CommandExecutionStatusFailed     CommandExecutionStatus = "failed"
	CommandExecutionStatusDeclined   CommandExecutionStatus = "declined"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v CommandExecutionStatus) IsKnown() bool {
	switch v {
	case CommandExecutionStatusInProgress,
		CommandExecutionStatusCompleted,
		CommandExecutionStatusFailed,
		CommandExecutionStatusDeclined:
		return true
	}
	return false
}

// String returns the wire value.
func (v CommandExecutionStatus) String() string { return string(v) }

type ConversationTextRole string

const (
	ConversationTextRoleUser      ConversationTextRole = "user"
	ConversationTextRoleDeveloper ConversationTextRole = "developer"
	ConversationTextRoleAssistant ConversationTextRole = "assistant"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ConversationTextRole) IsKnown() bool {
	switch v {
	case ConversationTextRoleUser,
		ConversationTextRoleDeveloper,
		ConversationTextRoleAssistant:
		return true
	}
	return false
}

// String returns the wire value.
func (v ConversationTextRole) String() string { return string(v) }

type DesktopOnboardingEntrypoint string

const (
	DesktopOnboardingEntrypointLifeSciences DesktopOnboardingEntrypoint = "life_sciences"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v DesktopOnboardingEntrypoint) IsKnown() bool {
	switch v {
	case DesktopOnboardingEntrypointLifeSciences:
		return true
	}
	return false
}

// String returns the wire value.
func (v DesktopOnboardingEntrypoint) String() string { return string(v) }

type DynamicToolCallStatus string

const (
	DynamicToolCallStatusInProgress DynamicToolCallStatus = "inProgress"
	DynamicToolCallStatusCompleted  DynamicToolCallStatus = "completed"
	DynamicToolCallStatusFailed     DynamicToolCallStatus = "failed"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v DynamicToolCallStatus) IsKnown() bool {
	switch v {
	case DynamicToolCallStatusInProgress,
		DynamicToolCallStatusCompleted,
		DynamicToolCallStatusFailed:
		return true
	}
	return false
}

// String returns the wire value.
func (v DynamicToolCallStatus) String() string { return string(v) }

type ExternalAgentConfigMigrationItemType string

const (
	ExternalAgentConfigMigrationItemTypeAgentsMD        ExternalAgentConfigMigrationItemType = "AGENTS_MD"
	ExternalAgentConfigMigrationItemTypeConfig          ExternalAgentConfigMigrationItemType = "CONFIG"
	ExternalAgentConfigMigrationItemTypeSkills          ExternalAgentConfigMigrationItemType = "SKILLS"
	ExternalAgentConfigMigrationItemTypePlugins         ExternalAgentConfigMigrationItemType = "PLUGINS"
	ExternalAgentConfigMigrationItemTypeMCPServerConfig ExternalAgentConfigMigrationItemType = "MCP_SERVER_CONFIG"
	ExternalAgentConfigMigrationItemTypeSubagents       ExternalAgentConfigMigrationItemType = "SUBAGENTS"
	ExternalAgentConfigMigrationItemTypeHooks           ExternalAgentConfigMigrationItemType = "HOOKS"
	ExternalAgentConfigMigrationItemTypeCommands        ExternalAgentConfigMigrationItemType = "COMMANDS"
	ExternalAgentConfigMigrationItemTypeMemory          ExternalAgentConfigMigrationItemType = "MEMORY"
	ExternalAgentConfigMigrationItemTypeSessions        ExternalAgentConfigMigrationItemType = "SESSIONS"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ExternalAgentConfigMigrationItemType) IsKnown() bool {
	switch v {
	case ExternalAgentConfigMigrationItemTypeAgentsMD,
		ExternalAgentConfigMigrationItemTypeConfig,
		ExternalAgentConfigMigrationItemTypeSkills,
		ExternalAgentConfigMigrationItemTypePlugins,
		ExternalAgentConfigMigrationItemTypeMCPServerConfig,
		ExternalAgentConfigMigrationItemTypeSubagents,
		ExternalAgentConfigMigrationItemTypeHooks,
		ExternalAgentConfigMigrationItemTypeCommands,
		ExternalAgentConfigMigrationItemTypeMemory,
		ExternalAgentConfigMigrationItemTypeSessions:
		return true
	}
	return false
}

// String returns the wire value.
func (v ExternalAgentConfigMigrationItemType) String() string { return string(v) }

type ExternalAgentDetectedConnectorSource string

const (
	ExternalAgentDetectedConnectorSourceRemoteMCPServersConfig ExternalAgentDetectedConnectorSource = "remoteMcpServersConfig"
	ExternalAgentDetectedConnectorSourceSessionToolUse         ExternalAgentDetectedConnectorSource = "sessionToolUse"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ExternalAgentDetectedConnectorSource) IsKnown() bool {
	switch v {
	case ExternalAgentDetectedConnectorSourceRemoteMCPServersConfig,
		ExternalAgentDetectedConnectorSourceSessionToolUse:
		return true
	}
	return false
}

// String returns the wire value.
func (v ExternalAgentDetectedConnectorSource) String() string { return string(v) }

type ExternalAgentImportedConnectorSource string

const (
	ExternalAgentImportedConnectorSourceRemoteMCPServersConfig ExternalAgentImportedConnectorSource = "remoteMcpServersConfig"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ExternalAgentImportedConnectorSource) IsKnown() bool {
	switch v {
	case ExternalAgentImportedConnectorSourceRemoteMCPServersConfig:
		return true
	}
	return false
}

// String returns the wire value.
func (v ExternalAgentImportedConnectorSource) String() string { return string(v) }

type FileSystemAccessMode string

const (
	FileSystemAccessModeRead  FileSystemAccessMode = "read"
	FileSystemAccessModeWrite FileSystemAccessMode = "write"
	FileSystemAccessModeDeny  FileSystemAccessMode = "deny"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v FileSystemAccessMode) IsKnown() bool {
	switch v {
	case FileSystemAccessModeRead,
		FileSystemAccessModeWrite,
		FileSystemAccessModeDeny:
		return true
	}
	return false
}

// String returns the wire value.
func (v FileSystemAccessMode) String() string { return string(v) }

type ForcedLoginMethod string

const (
	ForcedLoginMethodChatgpt ForcedLoginMethod = "chatgpt"
	ForcedLoginMethodAPI     ForcedLoginMethod = "api"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ForcedLoginMethod) IsKnown() bool {
	switch v {
	case ForcedLoginMethodChatgpt,
		ForcedLoginMethodAPI:
		return true
	}
	return false
}

// String returns the wire value.
func (v ForcedLoginMethod) String() string { return string(v) }

type FuzzyFileSearchMatchType string

const (
	FuzzyFileSearchMatchTypeFile      FuzzyFileSearchMatchType = "file"
	FuzzyFileSearchMatchTypeDirectory FuzzyFileSearchMatchType = "directory"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v FuzzyFileSearchMatchType) IsKnown() bool {
	switch v {
	case FuzzyFileSearchMatchTypeFile,
		FuzzyFileSearchMatchTypeDirectory:
		return true
	}
	return false
}

// String returns the wire value.
func (v FuzzyFileSearchMatchType) String() string { return string(v) }

// [UNSTABLE] Lifecycle state for an approval auto-review.
type GuardianApprovalReviewStatus string

const (
	GuardianApprovalReviewStatusInProgress GuardianApprovalReviewStatus = "inProgress"
	GuardianApprovalReviewStatusApproved   GuardianApprovalReviewStatus = "approved"
	GuardianApprovalReviewStatusDenied     GuardianApprovalReviewStatus = "denied"
	GuardianApprovalReviewStatusTimedOut   GuardianApprovalReviewStatus = "timedOut"
	GuardianApprovalReviewStatusAborted    GuardianApprovalReviewStatus = "aborted"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v GuardianApprovalReviewStatus) IsKnown() bool {
	switch v {
	case GuardianApprovalReviewStatusInProgress,
		GuardianApprovalReviewStatusApproved,
		GuardianApprovalReviewStatusDenied,
		GuardianApprovalReviewStatusTimedOut,
		GuardianApprovalReviewStatusAborted:
		return true
	}
	return false
}

// String returns the wire value.
func (v GuardianApprovalReviewStatus) String() string { return string(v) }

type GuardianCommandSource string

const (
	GuardianCommandSourceShell       GuardianCommandSource = "shell"
	GuardianCommandSourceUnifiedExec GuardianCommandSource = "unifiedExec"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v GuardianCommandSource) IsKnown() bool {
	switch v {
	case GuardianCommandSourceShell,
		GuardianCommandSourceUnifiedExec:
		return true
	}
	return false
}

// String returns the wire value.
func (v GuardianCommandSource) String() string { return string(v) }

// [UNSTABLE] Risk level assigned by approval auto-review.
type GuardianRiskLevel string

const (
	GuardianRiskLevelLow      GuardianRiskLevel = "low"
	GuardianRiskLevelMedium   GuardianRiskLevel = "medium"
	GuardianRiskLevelHigh     GuardianRiskLevel = "high"
	GuardianRiskLevelCritical GuardianRiskLevel = "critical"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v GuardianRiskLevel) IsKnown() bool {
	switch v {
	case GuardianRiskLevelLow,
		GuardianRiskLevelMedium,
		GuardianRiskLevelHigh,
		GuardianRiskLevelCritical:
		return true
	}
	return false
}

// String returns the wire value.
func (v GuardianRiskLevel) String() string { return string(v) }

// [UNSTABLE] Authorization level assigned by approval auto-review.
type GuardianUserAuthorization string

const (
	GuardianUserAuthorizationUnknown GuardianUserAuthorization = "unknown"
	GuardianUserAuthorizationLow     GuardianUserAuthorization = "low"
	GuardianUserAuthorizationMedium  GuardianUserAuthorization = "medium"
	GuardianUserAuthorizationHigh    GuardianUserAuthorization = "high"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v GuardianUserAuthorization) IsKnown() bool {
	switch v {
	case GuardianUserAuthorizationUnknown,
		GuardianUserAuthorizationLow,
		GuardianUserAuthorizationMedium,
		GuardianUserAuthorizationHigh:
		return true
	}
	return false
}

// String returns the wire value.
func (v GuardianUserAuthorization) String() string { return string(v) }

type HookEventName string

const (
	HookEventNamePreToolUse        HookEventName = "preToolUse"
	HookEventNamePermissionRequest HookEventName = "permissionRequest"
	HookEventNamePostToolUse       HookEventName = "postToolUse"
	HookEventNamePreCompact        HookEventName = "preCompact"
	HookEventNamePostCompact       HookEventName = "postCompact"
	HookEventNameSessionStart      HookEventName = "sessionStart"
	HookEventNameSessionEnd        HookEventName = "sessionEnd"
	HookEventNameUserPromptSubmit  HookEventName = "userPromptSubmit"
	HookEventNameSubagentStart     HookEventName = "subagentStart"
	HookEventNameSubagentStop      HookEventName = "subagentStop"
	HookEventNameStop              HookEventName = "stop"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v HookEventName) IsKnown() bool {
	switch v {
	case HookEventNamePreToolUse,
		HookEventNamePermissionRequest,
		HookEventNamePostToolUse,
		HookEventNamePreCompact,
		HookEventNamePostCompact,
		HookEventNameSessionStart,
		HookEventNameSessionEnd,
		HookEventNameUserPromptSubmit,
		HookEventNameSubagentStart,
		HookEventNameSubagentStop,
		HookEventNameStop:
		return true
	}
	return false
}

// String returns the wire value.
func (v HookEventName) String() string { return string(v) }

type HookExecutionMode string

const (
	HookExecutionModeSync  HookExecutionMode = "sync"
	HookExecutionModeAsync HookExecutionMode = "async"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v HookExecutionMode) IsKnown() bool {
	switch v {
	case HookExecutionModeSync,
		HookExecutionModeAsync:
		return true
	}
	return false
}

// String returns the wire value.
func (v HookExecutionMode) String() string { return string(v) }

type HookHandlerType string

const (
	HookHandlerTypeCommand HookHandlerType = "command"
	HookHandlerTypeMCPTool HookHandlerType = "mcpTool"
	HookHandlerTypePrompt  HookHandlerType = "prompt"
	HookHandlerTypeAgent   HookHandlerType = "agent"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v HookHandlerType) IsKnown() bool {
	switch v {
	case HookHandlerTypeCommand,
		HookHandlerTypeMCPTool,
		HookHandlerTypePrompt,
		HookHandlerTypeAgent:
		return true
	}
	return false
}

// String returns the wire value.
func (v HookHandlerType) String() string { return string(v) }

type HookOutputEntryKind string

const (
	HookOutputEntryKindWarning  HookOutputEntryKind = "warning"
	HookOutputEntryKindStop     HookOutputEntryKind = "stop"
	HookOutputEntryKindFeedback HookOutputEntryKind = "feedback"
	HookOutputEntryKindContext  HookOutputEntryKind = "context"
	HookOutputEntryKindError    HookOutputEntryKind = "error"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v HookOutputEntryKind) IsKnown() bool {
	switch v {
	case HookOutputEntryKindWarning,
		HookOutputEntryKindStop,
		HookOutputEntryKindFeedback,
		HookOutputEntryKindContext,
		HookOutputEntryKindError:
		return true
	}
	return false
}

// String returns the wire value.
func (v HookOutputEntryKind) String() string { return string(v) }

type HookRunStatus string

const (
	HookRunStatusRunning   HookRunStatus = "running"
	HookRunStatusCompleted HookRunStatus = "completed"
	HookRunStatusFailed    HookRunStatus = "failed"
	HookRunStatusBlocked   HookRunStatus = "blocked"
	HookRunStatusStopped   HookRunStatus = "stopped"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v HookRunStatus) IsKnown() bool {
	switch v {
	case HookRunStatusRunning,
		HookRunStatusCompleted,
		HookRunStatusFailed,
		HookRunStatusBlocked,
		HookRunStatusStopped:
		return true
	}
	return false
}

// String returns the wire value.
func (v HookRunStatus) String() string { return string(v) }

type HookScope string

const (
	HookScopeThread HookScope = "thread"
	HookScopeTurn   HookScope = "turn"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v HookScope) IsKnown() bool {
	switch v {
	case HookScopeThread,
		HookScopeTurn:
		return true
	}
	return false
}

// String returns the wire value.
func (v HookScope) String() string { return string(v) }

type HookSource string

const (
	HookSourceSystem                  HookSource = "system"
	HookSourceUser                    HookSource = "user"
	HookSourceProject                 HookSource = "project"
	HookSourceMdm                     HookSource = "mdm"
	HookSourceSessionFlags            HookSource = "sessionFlags"
	HookSourcePlugin                  HookSource = "plugin"
	HookSourceCloudRequirements       HookSource = "cloudRequirements"
	HookSourceCloudManagedConfig      HookSource = "cloudManagedConfig"
	HookSourceLegacyManagedConfigFile HookSource = "legacyManagedConfigFile"
	HookSourceLegacyManagedConfigMdm  HookSource = "legacyManagedConfigMdm"
	HookSourceUnknown                 HookSource = "unknown"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v HookSource) IsKnown() bool {
	switch v {
	case HookSourceSystem,
		HookSourceUser,
		HookSourceProject,
		HookSourceMdm,
		HookSourceSessionFlags,
		HookSourcePlugin,
		HookSourceCloudRequirements,
		HookSourceCloudManagedConfig,
		HookSourceLegacyManagedConfigFile,
		HookSourceLegacyManagedConfigMdm,
		HookSourceUnknown:
		return true
	}
	return false
}

// String returns the wire value.
func (v HookSource) String() string { return string(v) }

type HookTrustStatus string

const (
	HookTrustStatusManaged   HookTrustStatus = "managed"
	HookTrustStatusUntrusted HookTrustStatus = "untrusted"
	HookTrustStatusTrusted   HookTrustStatus = "trusted"
	HookTrustStatusModified  HookTrustStatus = "modified"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v HookTrustStatus) IsKnown() bool {
	switch v {
	case HookTrustStatusManaged,
		HookTrustStatusUntrusted,
		HookTrustStatusTrusted,
		HookTrustStatusModified:
		return true
	}
	return false
}

// String returns the wire value.
func (v HookTrustStatus) String() string { return string(v) }

type ImageDetail string

const (
	ImageDetailAuto     ImageDetail = "auto"
	ImageDetailLow      ImageDetail = "low"
	ImageDetailHigh     ImageDetail = "high"
	ImageDetailOriginal ImageDetail = "original"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ImageDetail) IsKnown() bool {
	switch v {
	case ImageDetailAuto,
		ImageDetailLow,
		ImageDetailHigh,
		ImageDetailOriginal:
		return true
	}
	return false
}

// String returns the wire value.
func (v ImageDetail) String() string { return string(v) }

type LocalShellStatus string

const (
	LocalShellStatusCompleted  LocalShellStatus = "completed"
	LocalShellStatusInProgress LocalShellStatus = "in_progress"
	LocalShellStatusIncomplete LocalShellStatus = "incomplete"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v LocalShellStatus) IsKnown() bool {
	switch v {
	case LocalShellStatusCompleted,
		LocalShellStatusInProgress,
		LocalShellStatusIncomplete:
		return true
	}
	return false
}

// String returns the wire value.
func (v LocalShellStatus) String() string { return string(v) }

type LoginAppBrand string

const (
	LoginAppBrandCodex   LoginAppBrand = "codex"
	LoginAppBrandChatgpt LoginAppBrand = "chatgpt"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v LoginAppBrand) IsKnown() bool {
	switch v {
	case LoginAppBrandCodex,
		LoginAppBrandChatgpt:
		return true
	}
	return false
}

// String returns the wire value.
func (v LoginAppBrand) String() string { return string(v) }

type MCPAuthStatus string

const (
	MCPAuthStatusUnknown     MCPAuthStatus = "unknown"
	MCPAuthStatusUnsupported MCPAuthStatus = "unsupported"
	MCPAuthStatusNotLoggedIn MCPAuthStatus = "notLoggedIn"
	MCPAuthStatusBearerToken MCPAuthStatus = "bearerToken"
	MCPAuthStatusOAuth       MCPAuthStatus = "oAuth"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPAuthStatus) IsKnown() bool {
	switch v {
	case MCPAuthStatusUnknown,
		MCPAuthStatusUnsupported,
		MCPAuthStatusNotLoggedIn,
		MCPAuthStatusBearerToken,
		MCPAuthStatusOAuth:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPAuthStatus) String() string { return string(v) }

type MCPElicitationArrayType string

const (
	MCPElicitationArrayTypeArray MCPElicitationArrayType = "array"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPElicitationArrayType) IsKnown() bool {
	switch v {
	case MCPElicitationArrayTypeArray:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPElicitationArrayType) String() string { return string(v) }

type MCPElicitationBooleanType string

const (
	MCPElicitationBooleanTypeBoolean MCPElicitationBooleanType = "boolean"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPElicitationBooleanType) IsKnown() bool {
	switch v {
	case MCPElicitationBooleanTypeBoolean:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPElicitationBooleanType) String() string { return string(v) }

type MCPElicitationNumberType string

const (
	MCPElicitationNumberTypeNumber  MCPElicitationNumberType = "number"
	MCPElicitationNumberTypeInteger MCPElicitationNumberType = "integer"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPElicitationNumberType) IsKnown() bool {
	switch v {
	case MCPElicitationNumberTypeNumber,
		MCPElicitationNumberTypeInteger:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPElicitationNumberType) String() string { return string(v) }

type MCPElicitationObjectType string

const (
	MCPElicitationObjectTypeObject MCPElicitationObjectType = "object"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPElicitationObjectType) IsKnown() bool {
	switch v {
	case MCPElicitationObjectTypeObject:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPElicitationObjectType) String() string { return string(v) }

type MCPElicitationStringFormat string

const (
	MCPElicitationStringFormatEmail    MCPElicitationStringFormat = "email"
	MCPElicitationStringFormatURI      MCPElicitationStringFormat = "uri"
	MCPElicitationStringFormatDate     MCPElicitationStringFormat = "date"
	MCPElicitationStringFormatDateTime MCPElicitationStringFormat = "date-time"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPElicitationStringFormat) IsKnown() bool {
	switch v {
	case MCPElicitationStringFormatEmail,
		MCPElicitationStringFormatURI,
		MCPElicitationStringFormatDate,
		MCPElicitationStringFormatDateTime:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPElicitationStringFormat) String() string { return string(v) }

type MCPElicitationStringType string

const (
	MCPElicitationStringTypeString MCPElicitationStringType = "string"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPElicitationStringType) IsKnown() bool {
	switch v {
	case MCPElicitationStringTypeString:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPElicitationStringType) String() string { return string(v) }

type MCPServerElicitationAction string

const (
	MCPServerElicitationActionAccept  MCPServerElicitationAction = "accept"
	MCPServerElicitationActionDecline MCPServerElicitationAction = "decline"
	MCPServerElicitationActionCancel  MCPServerElicitationAction = "cancel"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPServerElicitationAction) IsKnown() bool {
	switch v {
	case MCPServerElicitationActionAccept,
		MCPServerElicitationActionDecline,
		MCPServerElicitationActionCancel:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPServerElicitationAction) String() string { return string(v) }

type MCPServerOAuthClientRegistration string

const (
	MCPServerOAuthClientRegistrationAuto MCPServerOAuthClientRegistration = "auto"
	MCPServerOAuthClientRegistrationCimd MCPServerOAuthClientRegistration = "cimd"
	MCPServerOAuthClientRegistrationDcr  MCPServerOAuthClientRegistration = "dcr"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPServerOAuthClientRegistration) IsKnown() bool {
	switch v {
	case MCPServerOAuthClientRegistrationAuto,
		MCPServerOAuthClientRegistrationCimd,
		MCPServerOAuthClientRegistrationDcr:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPServerOAuthClientRegistration) String() string { return string(v) }

type MCPServerStartupFailureReason string

const (
	MCPServerStartupFailureReasonReauthenticationRequired MCPServerStartupFailureReason = "reauthenticationRequired"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPServerStartupFailureReason) IsKnown() bool {
	switch v {
	case MCPServerStartupFailureReasonReauthenticationRequired:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPServerStartupFailureReason) String() string { return string(v) }

type MCPServerStartupState string

const (
	MCPServerStartupStateStarting  MCPServerStartupState = "starting"
	MCPServerStartupStateReady     MCPServerStartupState = "ready"
	MCPServerStartupStateFailed    MCPServerStartupState = "failed"
	MCPServerStartupStateCancelled MCPServerStartupState = "cancelled"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPServerStartupState) IsKnown() bool {
	switch v {
	case MCPServerStartupStateStarting,
		MCPServerStartupStateReady,
		MCPServerStartupStateFailed,
		MCPServerStartupStateCancelled:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPServerStartupState) String() string { return string(v) }

type MCPServerStatusDetail string

const (
	MCPServerStatusDetailFull             MCPServerStatusDetail = "full"
	MCPServerStatusDetailToolsAndAuthOnly MCPServerStatusDetail = "toolsAndAuthOnly"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPServerStatusDetail) IsKnown() bool {
	switch v {
	case MCPServerStatusDetailFull,
		MCPServerStatusDetailToolsAndAuthOnly:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPServerStatusDetail) String() string { return string(v) }

type MCPToolCallStatus string

const (
	MCPToolCallStatusInProgress MCPToolCallStatus = "inProgress"
	MCPToolCallStatusCompleted  MCPToolCallStatus = "completed"
	MCPToolCallStatusFailed     MCPToolCallStatus = "failed"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MCPToolCallStatus) IsKnown() bool {
	switch v {
	case MCPToolCallStatusInProgress,
		MCPToolCallStatusCompleted,
		MCPToolCallStatusFailed:
		return true
	}
	return false
}

// String returns the wire value.
func (v MCPToolCallStatus) String() string { return string(v) }

type MergeStrategy string

const (
	MergeStrategyReplace MergeStrategy = "replace"
	MergeStrategyUpsert  MergeStrategy = "upsert"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MergeStrategy) IsKnown() bool {
	switch v {
	case MergeStrategyReplace,
		MergeStrategyUpsert:
		return true
	}
	return false
}

// String returns the wire value.
func (v MergeStrategy) String() string { return string(v) }

// Initial collaboration mode to use when the TUI starts.
type ModeKind string

const (
	ModeKindPlan    ModeKind = "plan"
	ModeKindDefault ModeKind = "default"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ModeKind) IsKnown() bool {
	switch v {
	case ModeKindPlan,
		ModeKindDefault:
		return true
	}
	return false
}

// String returns the wire value.
func (v ModeKind) String() string { return string(v) }

type ModelRerouteReason string

const (
	ModelRerouteReasonHighRiskCyberActivity ModelRerouteReason = "highRiskCyberActivity"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ModelRerouteReason) IsKnown() bool {
	switch v {
	case ModelRerouteReasonHighRiskCyberActivity:
		return true
	}
	return false
}

// String returns the wire value.
func (v ModelRerouteReason) String() string { return string(v) }

type ModelVerification string

const (
	ModelVerificationTrustedAccessForCyber ModelVerification = "trustedAccessForCyber"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ModelVerification) IsKnown() bool {
	switch v {
	case ModelVerificationTrustedAccessForCyber:
		return true
	}
	return false
}

// String returns the wire value.
func (v ModelVerification) String() string { return string(v) }

// Multi-agent runtime supported by a model.
type MultiAgentVersion string

const (
	MultiAgentVersionDisabled MultiAgentVersion = "disabled"
	MultiAgentVersionV1       MultiAgentVersion = "v1"
	MultiAgentVersionV2       MultiAgentVersion = "v2"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v MultiAgentVersion) IsKnown() bool {
	switch v {
	case MultiAgentVersionDisabled,
		MultiAgentVersionV1,
		MultiAgentVersionV2:
		return true
	}
	return false
}

// String returns the wire value.
func (v MultiAgentVersion) String() string { return string(v) }

type NetworkAccess string

const (
	NetworkAccessRestricted NetworkAccess = "restricted"
	NetworkAccessEnabled    NetworkAccess = "enabled"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v NetworkAccess) IsKnown() bool {
	switch v {
	case NetworkAccessRestricted,
		NetworkAccessEnabled:
		return true
	}
	return false
}

// String returns the wire value.
func (v NetworkAccess) String() string { return string(v) }

type NetworkApprovalProtocol string

const (
	NetworkApprovalProtocolHTTP      NetworkApprovalProtocol = "http"
	NetworkApprovalProtocolHTTPS     NetworkApprovalProtocol = "https"
	NetworkApprovalProtocolSocks5Tcp NetworkApprovalProtocol = "socks5Tcp"
	NetworkApprovalProtocolSocks5Udp NetworkApprovalProtocol = "socks5Udp"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v NetworkApprovalProtocol) IsKnown() bool {
	switch v {
	case NetworkApprovalProtocolHTTP,
		NetworkApprovalProtocolHTTPS,
		NetworkApprovalProtocolSocks5Tcp,
		NetworkApprovalProtocolSocks5Udp:
		return true
	}
	return false
}

// String returns the wire value.
func (v NetworkApprovalProtocol) String() string { return string(v) }

type NetworkDomainPermission string

const (
	NetworkDomainPermissionAllow NetworkDomainPermission = "allow"
	NetworkDomainPermissionDeny  NetworkDomainPermission = "deny"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v NetworkDomainPermission) IsKnown() bool {
	switch v {
	case NetworkDomainPermissionAllow,
		NetworkDomainPermissionDeny:
		return true
	}
	return false
}

// String returns the wire value.
func (v NetworkDomainPermission) String() string { return string(v) }

type NetworkPolicyRuleAction string

const (
	NetworkPolicyRuleActionAllow NetworkPolicyRuleAction = "allow"
	NetworkPolicyRuleActionDeny  NetworkPolicyRuleAction = "deny"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v NetworkPolicyRuleAction) IsKnown() bool {
	switch v {
	case NetworkPolicyRuleActionAllow,
		NetworkPolicyRuleActionDeny:
		return true
	}
	return false
}

// String returns the wire value.
func (v NetworkPolicyRuleAction) String() string { return string(v) }

type NetworkUnixSocketPermission string

const (
	NetworkUnixSocketPermissionAllow NetworkUnixSocketPermission = "allow"
	NetworkUnixSocketPermissionDeny  NetworkUnixSocketPermission = "deny"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v NetworkUnixSocketPermission) IsKnown() bool {
	switch v {
	case NetworkUnixSocketPermissionAllow,
		NetworkUnixSocketPermissionDeny:
		return true
	}
	return false
}

// String returns the wire value.
func (v NetworkUnixSocketPermission) String() string { return string(v) }

type NonSteerableTurnKind string

const (
	NonSteerableTurnKindReview  NonSteerableTurnKind = "review"
	NonSteerableTurnKindCompact NonSteerableTurnKind = "compact"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v NonSteerableTurnKind) IsKnown() bool {
	switch v {
	case NonSteerableTurnKindReview,
		NonSteerableTurnKindCompact:
		return true
	}
	return false
}

// String returns the wire value.
func (v NonSteerableTurnKind) String() string { return string(v) }

type PatchApplyStatus string

const (
	PatchApplyStatusInProgress PatchApplyStatus = "inProgress"
	PatchApplyStatusCompleted  PatchApplyStatus = "completed"
	PatchApplyStatusFailed     PatchApplyStatus = "failed"
	PatchApplyStatusDeclined   PatchApplyStatus = "declined"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PatchApplyStatus) IsKnown() bool {
	switch v {
	case PatchApplyStatusInProgress,
		PatchApplyStatusCompleted,
		PatchApplyStatusFailed,
		PatchApplyStatusDeclined:
		return true
	}
	return false
}

// String returns the wire value.
func (v PatchApplyStatus) String() string { return string(v) }

type PermissionGrantScope string

const (
	PermissionGrantScopeTurn    PermissionGrantScope = "turn"
	PermissionGrantScopeSession PermissionGrantScope = "session"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PermissionGrantScope) IsKnown() bool {
	switch v {
	case PermissionGrantScopeTurn,
		PermissionGrantScopeSession:
		return true
	}
	return false
}

// String returns the wire value.
func (v PermissionGrantScope) String() string { return string(v) }

type Personality string

const (
	PersonalityNone      Personality = "none"
	PersonalityFriendly  Personality = "friendly"
	PersonalityPragmatic Personality = "pragmatic"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v Personality) IsKnown() bool {
	switch v {
	case PersonalityNone,
		PersonalityFriendly,
		PersonalityPragmatic:
		return true
	}
	return false
}

// String returns the wire value.
func (v Personality) String() string { return string(v) }

type PlanType string

const (
	PlanTypeFree                        PlanType = "free"
	PlanTypeGo                          PlanType = "go"
	PlanTypePlus                        PlanType = "plus"
	PlanTypePro                         PlanType = "pro"
	PlanTypeProlite                     PlanType = "prolite"
	PlanTypeTeam                        PlanType = "team"
	PlanTypeSelfServeBusinessProlite    PlanType = "self_serve_business_prolite"
	PlanTypeSelfServeBusinessUsageBased PlanType = "self_serve_business_usage_based"
	PlanTypeBusiness                    PlanType = "business"
	PlanTypeEnt26                       PlanType = "ent26"
	PlanTypeEnterpriseCbpAutomation     PlanType = "enterprise_cbp_automation"
	PlanTypeEnterpriseCbpUsageBased     PlanType = "enterprise_cbp_usage_based"
	PlanTypeEnterprise                  PlanType = "enterprise"
	PlanTypeEdu                         PlanType = "edu"
	PlanTypeEduPlus                     PlanType = "edu_plus"
	PlanTypeEduPro                      PlanType = "edu_pro"
	PlanTypeUnknown                     PlanType = "unknown"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PlanType) IsKnown() bool {
	switch v {
	case PlanTypeFree,
		PlanTypeGo,
		PlanTypePlus,
		PlanTypePro,
		PlanTypeProlite,
		PlanTypeTeam,
		PlanTypeSelfServeBusinessProlite,
		PlanTypeSelfServeBusinessUsageBased,
		PlanTypeBusiness,
		PlanTypeEnt26,
		PlanTypeEnterpriseCbpAutomation,
		PlanTypeEnterpriseCbpUsageBased,
		PlanTypeEnterprise,
		PlanTypeEdu,
		PlanTypeEduPlus,
		PlanTypeEduPro,
		PlanTypeUnknown:
		return true
	}
	return false
}

// String returns the wire value.
func (v PlanType) String() string { return string(v) }

type PluginAuthPolicy string

const (
	PluginAuthPolicyOnInstall PluginAuthPolicy = "ON_INSTALL"
	PluginAuthPolicyOnUse     PluginAuthPolicy = "ON_USE"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginAuthPolicy) IsKnown() bool {
	switch v {
	case PluginAuthPolicyOnInstall,
		PluginAuthPolicyOnUse:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginAuthPolicy) String() string { return string(v) }

type PluginDisabledReason string

const (
	PluginDisabledReasonDisabledByAdmin        PluginDisabledReason = "disabled_by_admin"
	PluginDisabledReasonPlanNotEligible        PluginDisabledReason = "plan_not_eligible"
	PluginDisabledReasonRequiredAppUnavailable PluginDisabledReason = "required_app_unavailable"
	PluginDisabledReasonUnknown                PluginDisabledReason = "unknown"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginDisabledReason) IsKnown() bool {
	switch v {
	case PluginDisabledReasonDisabledByAdmin,
		PluginDisabledReasonPlanNotEligible,
		PluginDisabledReasonRequiredAppUnavailable,
		PluginDisabledReasonUnknown:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginDisabledReason) String() string { return string(v) }

type PluginInstallPolicy string

const (
	PluginInstallPolicyNotAvailable       PluginInstallPolicy = "NOT_AVAILABLE"
	PluginInstallPolicyAvailable          PluginInstallPolicy = "AVAILABLE"
	PluginInstallPolicyInstalledByDefault PluginInstallPolicy = "INSTALLED_BY_DEFAULT"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginInstallPolicy) IsKnown() bool {
	switch v {
	case PluginInstallPolicyNotAvailable,
		PluginInstallPolicyAvailable,
		PluginInstallPolicyInstalledByDefault:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginInstallPolicy) String() string { return string(v) }

type PluginInstallPolicySource string

const (
	PluginInstallPolicySourceWorkspaceSetting     PluginInstallPolicySource = "WORKSPACE_SETTING"
	PluginInstallPolicySourceImplicitCanonicalApp PluginInstallPolicySource = "IMPLICIT_CANONICAL_APP"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginInstallPolicySource) IsKnown() bool {
	switch v {
	case PluginInstallPolicySourceWorkspaceSetting,
		PluginInstallPolicySourceImplicitCanonicalApp:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginInstallPolicySource) String() string { return string(v) }

type PluginListMarketplaceKind string

const (
	PluginListMarketplaceKindLocal              PluginListMarketplaceKind = "local"
	PluginListMarketplaceKindVertical           PluginListMarketplaceKind = "vertical"
	PluginListMarketplaceKindWorkspaceDirectory PluginListMarketplaceKind = "workspace-directory"
	PluginListMarketplaceKindSharedWithMe       PluginListMarketplaceKind = "shared-with-me"
	PluginListMarketplaceKindCreatedByMeRemote  PluginListMarketplaceKind = "created-by-me-remote"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginListMarketplaceKind) IsKnown() bool {
	switch v {
	case PluginListMarketplaceKindLocal,
		PluginListMarketplaceKindVertical,
		PluginListMarketplaceKindWorkspaceDirectory,
		PluginListMarketplaceKindSharedWithMe,
		PluginListMarketplaceKindCreatedByMeRemote:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginListMarketplaceKind) String() string { return string(v) }

type PluginSearchScope string

const (
	PluginSearchScopeGlobal    PluginSearchScope = "global"
	PluginSearchScopeWorkspace PluginSearchScope = "workspace"
	PluginSearchScopePersonal  PluginSearchScope = "personal"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginSearchScope) IsKnown() bool {
	switch v {
	case PluginSearchScopeGlobal,
		PluginSearchScopeWorkspace,
		PluginSearchScopePersonal:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginSearchScope) String() string { return string(v) }

type PluginShareDiscoverability string

const (
	PluginShareDiscoverabilityListed   PluginShareDiscoverability = "LISTED"
	PluginShareDiscoverabilityUnlisted PluginShareDiscoverability = "UNLISTED"
	PluginShareDiscoverabilityPrivate  PluginShareDiscoverability = "PRIVATE"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginShareDiscoverability) IsKnown() bool {
	switch v {
	case PluginShareDiscoverabilityListed,
		PluginShareDiscoverabilityUnlisted,
		PluginShareDiscoverabilityPrivate:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginShareDiscoverability) String() string { return string(v) }

type PluginSharePrincipalRole string

const (
	PluginSharePrincipalRoleReader PluginSharePrincipalRole = "reader"
	PluginSharePrincipalRoleEditor PluginSharePrincipalRole = "editor"
	PluginSharePrincipalRoleOwner  PluginSharePrincipalRole = "owner"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginSharePrincipalRole) IsKnown() bool {
	switch v {
	case PluginSharePrincipalRoleReader,
		PluginSharePrincipalRoleEditor,
		PluginSharePrincipalRoleOwner:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginSharePrincipalRole) String() string { return string(v) }

type PluginSharePrincipalType string

const (
	PluginSharePrincipalTypeUser      PluginSharePrincipalType = "user"
	PluginSharePrincipalTypeGroup     PluginSharePrincipalType = "group"
	PluginSharePrincipalTypeWorkspace PluginSharePrincipalType = "workspace"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginSharePrincipalType) IsKnown() bool {
	switch v {
	case PluginSharePrincipalTypeUser,
		PluginSharePrincipalTypeGroup,
		PluginSharePrincipalTypeWorkspace:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginSharePrincipalType) String() string { return string(v) }

type PluginShareTargetRole string

const (
	PluginShareTargetRoleReader PluginShareTargetRole = "reader"
	PluginShareTargetRoleEditor PluginShareTargetRole = "editor"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginShareTargetRole) IsKnown() bool {
	switch v {
	case PluginShareTargetRoleReader,
		PluginShareTargetRoleEditor:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginShareTargetRole) String() string { return string(v) }

type PluginShareUpdateDiscoverability string

const (
	PluginShareUpdateDiscoverabilityUnlisted PluginShareUpdateDiscoverability = "UNLISTED"
	PluginShareUpdateDiscoverabilityPrivate  PluginShareUpdateDiscoverability = "PRIVATE"
	PluginShareUpdateDiscoverabilityListed   PluginShareUpdateDiscoverability = "LISTED"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v PluginShareUpdateDiscoverability) IsKnown() bool {
	switch v {
	case PluginShareUpdateDiscoverabilityUnlisted,
		PluginShareUpdateDiscoverabilityPrivate,
		PluginShareUpdateDiscoverabilityListed:
		return true
	}
	return false
}

// String returns the wire value.
func (v PluginShareUpdateDiscoverability) String() string { return string(v) }

type ProjectChangeType string

const (
	ProjectChangeTypeCreated ProjectChangeType = "created"
	ProjectChangeTypeUpdated ProjectChangeType = "updated"
	ProjectChangeTypeDeleted ProjectChangeType = "deleted"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ProjectChangeType) IsKnown() bool {
	switch v {
	case ProjectChangeTypeCreated,
		ProjectChangeTypeUpdated,
		ProjectChangeTypeDeleted:
		return true
	}
	return false
}

// String returns the wire value.
func (v ProjectChangeType) String() string { return string(v) }

type RateLimitReachedType string

const (
	RateLimitReachedTypeRateLimitReached                 RateLimitReachedType = "rate_limit_reached"
	RateLimitReachedTypeWorkspaceOwnerCreditsDepleted    RateLimitReachedType = "workspace_owner_credits_depleted"
	RateLimitReachedTypeWorkspaceMemberCreditsDepleted   RateLimitReachedType = "workspace_member_credits_depleted"
	RateLimitReachedTypeWorkspaceOwnerUsageLimitReached  RateLimitReachedType = "workspace_owner_usage_limit_reached"
	RateLimitReachedTypeWorkspaceMemberUsageLimitReached RateLimitReachedType = "workspace_member_usage_limit_reached"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v RateLimitReachedType) IsKnown() bool {
	switch v {
	case RateLimitReachedTypeRateLimitReached,
		RateLimitReachedTypeWorkspaceOwnerCreditsDepleted,
		RateLimitReachedTypeWorkspaceMemberCreditsDepleted,
		RateLimitReachedTypeWorkspaceOwnerUsageLimitReached,
		RateLimitReachedTypeWorkspaceMemberUsageLimitReached:
		return true
	}
	return false
}

// String returns the wire value.
func (v RateLimitReachedType) String() string { return string(v) }

type RateLimitResetCreditStatus string

const (
	RateLimitResetCreditStatusAvailable RateLimitResetCreditStatus = "available"
	RateLimitResetCreditStatusRedeeming RateLimitResetCreditStatus = "redeeming"
	RateLimitResetCreditStatusRedeemed  RateLimitResetCreditStatus = "redeemed"
	RateLimitResetCreditStatusUnknown   RateLimitResetCreditStatus = "unknown"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v RateLimitResetCreditStatus) IsKnown() bool {
	switch v {
	case RateLimitResetCreditStatusAvailable,
		RateLimitResetCreditStatusRedeeming,
		RateLimitResetCreditStatusRedeemed,
		RateLimitResetCreditStatusUnknown:
		return true
	}
	return false
}

// String returns the wire value.
func (v RateLimitResetCreditStatus) String() string { return string(v) }

type RateLimitResetType string

const (
	RateLimitResetTypeCodexRateLimits RateLimitResetType = "codexRateLimits"
	RateLimitResetTypeUnknown         RateLimitResetType = "unknown"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v RateLimitResetType) IsKnown() bool {
	switch v {
	case RateLimitResetTypeCodexRateLimits,
		RateLimitResetTypeUnknown:
		return true
	}
	return false
}

// String returns the wire value.
func (v RateLimitResetType) String() string { return string(v) }

type RealtimeConversationVersion string

const (
	RealtimeConversationVersionV1 RealtimeConversationVersion = "v1"
	RealtimeConversationVersionV2 RealtimeConversationVersion = "v2"
	RealtimeConversationVersionV3 RealtimeConversationVersion = "v3"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v RealtimeConversationVersion) IsKnown() bool {
	switch v {
	case RealtimeConversationVersionV1,
		RealtimeConversationVersionV2,
		RealtimeConversationVersionV3:
		return true
	}
	return false
}

// String returns the wire value.
func (v RealtimeConversationVersion) String() string { return string(v) }

type RealtimeOutputModality string

const (
	RealtimeOutputModalityText  RealtimeOutputModality = "text"
	RealtimeOutputModalityAudio RealtimeOutputModality = "audio"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v RealtimeOutputModality) IsKnown() bool {
	switch v {
	case RealtimeOutputModalityText,
		RealtimeOutputModalityAudio:
		return true
	}
	return false
}

// String returns the wire value.
func (v RealtimeOutputModality) String() string { return string(v) }

type RealtimeVoice string

const (
	RealtimeVoiceAlloy   RealtimeVoice = "alloy"
	RealtimeVoiceArbor   RealtimeVoice = "arbor"
	RealtimeVoiceAsh     RealtimeVoice = "ash"
	RealtimeVoiceBallad  RealtimeVoice = "ballad"
	RealtimeVoiceBreeze  RealtimeVoice = "breeze"
	RealtimeVoiceCedar   RealtimeVoice = "cedar"
	RealtimeVoiceCoral   RealtimeVoice = "coral"
	RealtimeVoiceCove    RealtimeVoice = "cove"
	RealtimeVoiceEcho    RealtimeVoice = "echo"
	RealtimeVoiceEmber   RealtimeVoice = "ember"
	RealtimeVoiceJuniper RealtimeVoice = "juniper"
	RealtimeVoiceMaple   RealtimeVoice = "maple"
	RealtimeVoiceMarin   RealtimeVoice = "marin"
	RealtimeVoiceSage    RealtimeVoice = "sage"
	RealtimeVoiceShimmer RealtimeVoice = "shimmer"
	RealtimeVoiceSol     RealtimeVoice = "sol"
	RealtimeVoiceSpruce  RealtimeVoice = "spruce"
	RealtimeVoiceVale    RealtimeVoice = "vale"
	RealtimeVoiceVerse   RealtimeVoice = "verse"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v RealtimeVoice) IsKnown() bool {
	switch v {
	case RealtimeVoiceAlloy,
		RealtimeVoiceArbor,
		RealtimeVoiceAsh,
		RealtimeVoiceBallad,
		RealtimeVoiceBreeze,
		RealtimeVoiceCedar,
		RealtimeVoiceCoral,
		RealtimeVoiceCove,
		RealtimeVoiceEcho,
		RealtimeVoiceEmber,
		RealtimeVoiceJuniper,
		RealtimeVoiceMaple,
		RealtimeVoiceMarin,
		RealtimeVoiceSage,
		RealtimeVoiceShimmer,
		RealtimeVoiceSol,
		RealtimeVoiceSpruce,
		RealtimeVoiceVale,
		RealtimeVoiceVerse:
		return true
	}
	return false
}

// String returns the wire value.
func (v RealtimeVoice) String() string { return string(v) }

// EXPERIMENTAL: requires WithExperimentalAPI(). The server rejects this
// unless capabilities.experimentalApi was set during initialize.
type RemoteControlClientsListOrder string

const (
	RemoteControlClientsListOrderAsc  RemoteControlClientsListOrder = "asc"
	RemoteControlClientsListOrderDesc RemoteControlClientsListOrder = "desc"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v RemoteControlClientsListOrder) IsKnown() bool {
	switch v {
	case RemoteControlClientsListOrderAsc,
		RemoteControlClientsListOrderDesc:
		return true
	}
	return false
}

// String returns the wire value.
func (v RemoteControlClientsListOrder) String() string { return string(v) }

type RemoteControlConnectionStatus string

const (
	RemoteControlConnectionStatusDisabled   RemoteControlConnectionStatus = "disabled"
	RemoteControlConnectionStatusConnecting RemoteControlConnectionStatus = "connecting"
	RemoteControlConnectionStatusConnected  RemoteControlConnectionStatus = "connected"
	RemoteControlConnectionStatusErrored    RemoteControlConnectionStatus = "errored"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v RemoteControlConnectionStatus) IsKnown() bool {
	switch v {
	case RemoteControlConnectionStatusDisabled,
		RemoteControlConnectionStatusConnecting,
		RemoteControlConnectionStatusConnected,
		RemoteControlConnectionStatusErrored:
		return true
	}
	return false
}

// String returns the wire value.
func (v RemoteControlConnectionStatus) String() string { return string(v) }

type ResidencyRequirement string

const (
	ResidencyRequirementUs ResidencyRequirement = "us"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ResidencyRequirement) IsKnown() bool {
	switch v {
	case ResidencyRequirementUs:
		return true
	}
	return false
}

// String returns the wire value.
func (v ResidencyRequirement) String() string { return string(v) }

type ReviewDelivery string

const (
	ReviewDeliveryInline   ReviewDelivery = "inline"
	ReviewDeliveryDetached ReviewDelivery = "detached"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ReviewDelivery) IsKnown() bool {
	switch v {
	case ReviewDeliveryInline,
		ReviewDeliveryDetached:
		return true
	}
	return false
}

// String returns the wire value.
func (v ReviewDelivery) String() string { return string(v) }

type SandboxMode string

const (
	SandboxModeReadOnly         SandboxMode = "read-only"
	SandboxModeWorkspaceWrite   SandboxMode = "workspace-write"
	SandboxModeDangerFullAccess SandboxMode = "danger-full-access"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v SandboxMode) IsKnown() bool {
	switch v {
	case SandboxModeReadOnly,
		SandboxModeWorkspaceWrite,
		SandboxModeDangerFullAccess:
		return true
	}
	return false
}

// String returns the wire value.
func (v SandboxMode) String() string { return string(v) }

type ScheduledTaskWeekday string

const (
	ScheduledTaskWeekdayMo ScheduledTaskWeekday = "MO"
	ScheduledTaskWeekdayTu ScheduledTaskWeekday = "TU"
	ScheduledTaskWeekdayWe ScheduledTaskWeekday = "WE"
	ScheduledTaskWeekdayTh ScheduledTaskWeekday = "TH"
	ScheduledTaskWeekdayFr ScheduledTaskWeekday = "FR"
	ScheduledTaskWeekdaySa ScheduledTaskWeekday = "SA"
	ScheduledTaskWeekdaySu ScheduledTaskWeekday = "SU"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ScheduledTaskWeekday) IsKnown() bool {
	switch v {
	case ScheduledTaskWeekdayMo,
		ScheduledTaskWeekdayTu,
		ScheduledTaskWeekdayWe,
		ScheduledTaskWeekdayTh,
		ScheduledTaskWeekdayFr,
		ScheduledTaskWeekdaySa,
		ScheduledTaskWeekdaySu:
		return true
	}
	return false
}

// String returns the wire value.
func (v ScheduledTaskWeekday) String() string { return string(v) }

type SkillScope string

const (
	SkillScopeUser   SkillScope = "user"
	SkillScopeRepo   SkillScope = "repo"
	SkillScopeSystem SkillScope = "system"
	SkillScopeAdmin  SkillScope = "admin"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v SkillScope) IsKnown() bool {
	switch v {
	case SkillScopeUser,
		SkillScopeRepo,
		SkillScopeSystem,
		SkillScopeAdmin:
		return true
	}
	return false
}

// String returns the wire value.
func (v SkillScope) String() string { return string(v) }

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "asc"
	SortDirectionDesc SortDirection = "desc"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v SortDirection) IsKnown() bool {
	switch v {
	case SortDirectionAsc,
		SortDirectionDesc:
		return true
	}
	return false
}

// String returns the wire value.
func (v SortDirection) String() string { return string(v) }

type SubAgentActivityKind string

const (
	SubAgentActivityKindStarted     SubAgentActivityKind = "started"
	SubAgentActivityKindInteracted  SubAgentActivityKind = "interacted"
	SubAgentActivityKindInterrupted SubAgentActivityKind = "interrupted"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v SubAgentActivityKind) IsKnown() bool {
	switch v {
	case SubAgentActivityKindStarted,
		SubAgentActivityKindInteracted,
		SubAgentActivityKindInterrupted:
		return true
	}
	return false
}

// String returns the wire value.
func (v SubAgentActivityKind) String() string { return string(v) }

type ThreadActiveFlag string

const (
	ThreadActiveFlagWaitingOnApproval  ThreadActiveFlag = "waitingOnApproval"
	ThreadActiveFlagWaitingOnUserInput ThreadActiveFlag = "waitingOnUserInput"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ThreadActiveFlag) IsKnown() bool {
	switch v {
	case ThreadActiveFlagWaitingOnApproval,
		ThreadActiveFlagWaitingOnUserInput:
		return true
	}
	return false
}

// String returns the wire value.
func (v ThreadActiveFlag) String() string { return string(v) }

type ThreadGoalStatus string

const (
	ThreadGoalStatusActive        ThreadGoalStatus = "active"
	ThreadGoalStatusPaused        ThreadGoalStatus = "paused"
	ThreadGoalStatusBlocked       ThreadGoalStatus = "blocked"
	ThreadGoalStatusUsageLimited  ThreadGoalStatus = "usageLimited"
	ThreadGoalStatusBudgetLimited ThreadGoalStatus = "budgetLimited"
	ThreadGoalStatusComplete      ThreadGoalStatus = "complete"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ThreadGoalStatus) IsKnown() bool {
	switch v {
	case ThreadGoalStatusActive,
		ThreadGoalStatusPaused,
		ThreadGoalStatusBlocked,
		ThreadGoalStatusUsageLimited,
		ThreadGoalStatusBudgetLimited,
		ThreadGoalStatusComplete:
		return true
	}
	return false
}

// String returns the wire value.
func (v ThreadGoalStatus) String() string { return string(v) }

type ThreadHistoryMode string

const (
	ThreadHistoryModeLegacy    ThreadHistoryMode = "legacy"
	ThreadHistoryModePaginated ThreadHistoryMode = "paginated"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ThreadHistoryMode) IsKnown() bool {
	switch v {
	case ThreadHistoryModeLegacy,
		ThreadHistoryModePaginated:
		return true
	}
	return false
}

// String returns the wire value.
func (v ThreadHistoryMode) String() string { return string(v) }

type ThreadMemoryMode string

const (
	ThreadMemoryModeEnabled  ThreadMemoryMode = "enabled"
	ThreadMemoryModeDisabled ThreadMemoryMode = "disabled"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ThreadMemoryMode) IsKnown() bool {
	switch v {
	case ThreadMemoryModeEnabled,
		ThreadMemoryModeDisabled:
		return true
	}
	return false
}

// String returns the wire value.
func (v ThreadMemoryMode) String() string { return string(v) }

type ThreadSearchSortKey string

const (
	ThreadSearchSortKeyCreatedAt ThreadSearchSortKey = "created_at"
	ThreadSearchSortKeyUpdatedAt ThreadSearchSortKey = "updated_at"
	ThreadSearchSortKeyRecencyAt ThreadSearchSortKey = "recency_at"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ThreadSearchSortKey) IsKnown() bool {
	switch v {
	case ThreadSearchSortKeyCreatedAt,
		ThreadSearchSortKeyUpdatedAt,
		ThreadSearchSortKeyRecencyAt:
		return true
	}
	return false
}

// String returns the wire value.
func (v ThreadSearchSortKey) String() string { return string(v) }

type ThreadSortKey string

const (
	ThreadSortKeyCreatedAt       ThreadSortKey = "created_at"
	ThreadSortKeyUpdatedAt       ThreadSortKey = "updated_at"
	ThreadSortKeyRecencyAt       ThreadSortKey = "recency_at"
	ThreadSortKeySectionPosition ThreadSortKey = "section_position"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ThreadSortKey) IsKnown() bool {
	switch v {
	case ThreadSortKeyCreatedAt,
		ThreadSortKeyUpdatedAt,
		ThreadSortKeyRecencyAt,
		ThreadSortKeySectionPosition:
		return true
	}
	return false
}

// String returns the wire value.
func (v ThreadSortKey) String() string { return string(v) }

type ThreadSourceKind string

const (
	ThreadSourceKindCLI                 ThreadSourceKind = "cli"
	ThreadSourceKindVscode              ThreadSourceKind = "vscode"
	ThreadSourceKindExec                ThreadSourceKind = "exec"
	ThreadSourceKindAppServer           ThreadSourceKind = "appServer"
	ThreadSourceKindSubAgent            ThreadSourceKind = "subAgent"
	ThreadSourceKindSubAgentReview      ThreadSourceKind = "subAgentReview"
	ThreadSourceKindSubAgentCompact     ThreadSourceKind = "subAgentCompact"
	ThreadSourceKindSubAgentThreadSpawn ThreadSourceKind = "subAgentThreadSpawn"
	ThreadSourceKindSubAgentOther       ThreadSourceKind = "subAgentOther"
	ThreadSourceKindUnknown             ThreadSourceKind = "unknown"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ThreadSourceKind) IsKnown() bool {
	switch v {
	case ThreadSourceKindCLI,
		ThreadSourceKindVscode,
		ThreadSourceKindExec,
		ThreadSourceKindAppServer,
		ThreadSourceKindSubAgent,
		ThreadSourceKindSubAgentReview,
		ThreadSourceKindSubAgentCompact,
		ThreadSourceKindSubAgentThreadSpawn,
		ThreadSourceKindSubAgentOther,
		ThreadSourceKindUnknown:
		return true
	}
	return false
}

// String returns the wire value.
func (v ThreadSourceKind) String() string { return string(v) }

type ThreadStartSource string

const (
	ThreadStartSourceStartup ThreadStartSource = "startup"
	ThreadStartSourceClear   ThreadStartSource = "clear"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ThreadStartSource) IsKnown() bool {
	switch v {
	case ThreadStartSourceStartup,
		ThreadStartSourceClear:
		return true
	}
	return false
}

// String returns the wire value.
func (v ThreadStartSource) String() string { return string(v) }

type ThreadUnsubscribeStatus string

const (
	ThreadUnsubscribeStatusNotLoaded     ThreadUnsubscribeStatus = "notLoaded"
	ThreadUnsubscribeStatusNotSubscribed ThreadUnsubscribeStatus = "notSubscribed"
	ThreadUnsubscribeStatusUnsubscribed  ThreadUnsubscribeStatus = "unsubscribed"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v ThreadUnsubscribeStatus) IsKnown() bool {
	switch v {
	case ThreadUnsubscribeStatusNotLoaded,
		ThreadUnsubscribeStatusNotSubscribed,
		ThreadUnsubscribeStatusUnsubscribed:
		return true
	}
	return false
}

// String returns the wire value.
func (v ThreadUnsubscribeStatus) String() string { return string(v) }

type TurnPlanStepStatus string

const (
	TurnPlanStepStatusPending    TurnPlanStepStatus = "pending"
	TurnPlanStepStatusInProgress TurnPlanStepStatus = "inProgress"
	TurnPlanStepStatusCompleted  TurnPlanStepStatus = "completed"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v TurnPlanStepStatus) IsKnown() bool {
	switch v {
	case TurnPlanStepStatusPending,
		TurnPlanStepStatusInProgress,
		TurnPlanStepStatusCompleted:
		return true
	}
	return false
}

// String returns the wire value.
func (v TurnPlanStepStatus) String() string { return string(v) }

type TurnStatus string

const (
	TurnStatusCompleted   TurnStatus = "completed"
	TurnStatusInterrupted TurnStatus = "interrupted"
	TurnStatusFailed      TurnStatus = "failed"
	TurnStatusInProgress  TurnStatus = "inProgress"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v TurnStatus) IsKnown() bool {
	switch v {
	case TurnStatusCompleted,
		TurnStatusInterrupted,
		TurnStatusFailed,
		TurnStatusInProgress:
		return true
	}
	return false
}

// String returns the wire value.
func (v TurnStatus) String() string { return string(v) }

// Controls output length/detail on GPT-5 models via the Responses API. Serialized with lowercase values to match the OpenAI API.
type Verbosity string

const (
	VerbosityLow    Verbosity = "low"
	VerbosityMedium Verbosity = "medium"
	VerbosityHigh   Verbosity = "high"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v Verbosity) IsKnown() bool {
	switch v {
	case VerbosityLow,
		VerbosityMedium,
		VerbosityHigh:
		return true
	}
	return false
}

// String returns the wire value.
func (v Verbosity) String() string { return string(v) }

type WebSearchContextSize string

const (
	WebSearchContextSizeLow    WebSearchContextSize = "low"
	WebSearchContextSizeMedium WebSearchContextSize = "medium"
	WebSearchContextSizeHigh   WebSearchContextSize = "high"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v WebSearchContextSize) IsKnown() bool {
	switch v {
	case WebSearchContextSizeLow,
		WebSearchContextSizeMedium,
		WebSearchContextSizeHigh:
		return true
	}
	return false
}

// String returns the wire value.
func (v WebSearchContextSize) String() string { return string(v) }

type WebSearchMode string

const (
	WebSearchModeDisabled WebSearchMode = "disabled"
	WebSearchModeCached   WebSearchMode = "cached"
	WebSearchModeIndexed  WebSearchMode = "indexed"
	WebSearchModeLive     WebSearchMode = "live"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v WebSearchMode) IsKnown() bool {
	switch v {
	case WebSearchModeDisabled,
		WebSearchModeCached,
		WebSearchModeIndexed,
		WebSearchModeLive:
		return true
	}
	return false
}

// String returns the wire value.
func (v WebSearchMode) String() string { return string(v) }

type WindowsSandboxReadiness string

const (
	WindowsSandboxReadinessReady          WindowsSandboxReadiness = "ready"
	WindowsSandboxReadinessNotConfigured  WindowsSandboxReadiness = "notConfigured"
	WindowsSandboxReadinessUpdateRequired WindowsSandboxReadiness = "updateRequired"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v WindowsSandboxReadiness) IsKnown() bool {
	switch v {
	case WindowsSandboxReadinessReady,
		WindowsSandboxReadinessNotConfigured,
		WindowsSandboxReadinessUpdateRequired:
		return true
	}
	return false
}

// String returns the wire value.
func (v WindowsSandboxReadiness) String() string { return string(v) }

type WindowsSandboxSetupMode string

const (
	WindowsSandboxSetupModeElevated   WindowsSandboxSetupMode = "elevated"
	WindowsSandboxSetupModeUnelevated WindowsSandboxSetupMode = "unelevated"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v WindowsSandboxSetupMode) IsKnown() bool {
	switch v {
	case WindowsSandboxSetupModeElevated,
		WindowsSandboxSetupModeUnelevated:
		return true
	}
	return false
}

// String returns the wire value.
func (v WindowsSandboxSetupMode) String() string { return string(v) }

type WorkspaceMessageType string

const (
	WorkspaceMessageTypeHeadline     WorkspaceMessageType = "headline"
	WorkspaceMessageTypeAnnouncement WorkspaceMessageType = "announcement"
	WorkspaceMessageTypeUnknown      WorkspaceMessageType = "unknown"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v WorkspaceMessageType) IsKnown() bool {
	switch v {
	case WorkspaceMessageTypeHeadline,
		WorkspaceMessageTypeAnnouncement,
		WorkspaceMessageTypeUnknown:
		return true
	}
	return false
}

// String returns the wire value.
func (v WorkspaceMessageType) String() string { return string(v) }

type WriteStatus string

const (
	WriteStatusOk           WriteStatus = "ok"
	WriteStatusOkOverridden WriteStatus = "okOverridden"
)

// IsKnown reports whether v is a value this build recognizes. A newer
// server may send values that are not, and those are preserved as-is.
func (v WriteStatus) IsKnown() bool {
	switch v {
	case WriteStatusOk,
		WriteStatusOkOverridden:
		return true
	}
	return false
}

// String returns the wire value.
func (v WriteStatus) String() string { return string(v) }
