// Code generated by internal/cmd/schemagen. DO NOT EDIT.
//
// Source: internal/schemas, generated from codex-cli 0.149.0.
// Regenerate with `make generate`.

package protocol

// Methods the client sends to the server, each expecting a result.
const (
	// MethodAccountBedrockDiscover is experimental; see WithExperimentalAPI.
	MethodAccountBedrockDiscover = "account/bedrock/discover"
	// MethodAccountBedrockSetup is experimental; see WithExperimentalAPI.
	MethodAccountBedrockSetup                = "account/bedrock/setup"
	MethodAccountLoginCancel                 = "account/login/cancel"
	MethodAccountLoginStart                  = "account/login/start"
	MethodAccountLogout                      = "account/logout"
	MethodAccountRateLimitResetCreditConsume = "account/rateLimitResetCredit/consume"
	MethodAccountRateLimitsRead              = "account/rateLimits/read"
	MethodAccountRead                        = "account/read"
	MethodAccountSendAddCreditsNudgeEmail    = "account/sendAddCreditsNudgeEmail"
	MethodAccountUsageRead                   = "account/usage/read"
	MethodAccountWorkspaceMessagesRead       = "account/workspaceMessages/read"
	MethodAppInstalled                       = "app/installed"
	MethodAppList                            = "app/list"
	MethodAppRead                            = "app/read"
	// MethodCollaborationModeList is experimental; see WithExperimentalAPI.
	MethodCollaborationModeList  = "collaborationMode/list"
	MethodCommandExec            = "command/exec"
	MethodCommandExecResize      = "command/exec/resize"
	MethodCommandExecTerminate   = "command/exec/terminate"
	MethodCommandExecWrite       = "command/exec/write"
	MethodConfigBatchWrite       = "config/batchWrite"
	MethodConfigMcpServerReload  = "config/mcpServer/reload"
	MethodConfigRead             = "config/read"
	MethodConfigValueWrite       = "config/value/write"
	MethodConfigRequirementsRead = "configRequirements/read"
	// MethodEnvironmentAdd is experimental; see WithExperimentalAPI.
	MethodEnvironmentAdd = "environment/add"
	// MethodEnvironmentInfo is experimental; see WithExperimentalAPI.
	MethodEnvironmentInfo = "environment/info"
	// MethodEnvironmentStatus is experimental; see WithExperimentalAPI.
	MethodEnvironmentStatus                      = "environment/status"
	MethodExperimentalFeatureEnablementSet       = "experimentalFeature/enablement/set"
	MethodExperimentalFeatureList                = "experimentalFeature/list"
	MethodExternalAgentConfigDetect              = "externalAgentConfig/detect"
	MethodExternalAgentConfigImport              = "externalAgentConfig/import"
	MethodExternalAgentConfigImportReadHistories = "externalAgentConfig/import/readHistories"
	MethodExternalAgentConfigImportRecordHistory = "externalAgentConfig/import/recordHistory"
	MethodFeedbackUpload                         = "feedback/upload"
	MethodFsCopy                                 = "fs/copy"
	MethodFsCreateDirectory                      = "fs/createDirectory"
	MethodFsGetMetadata                          = "fs/getMetadata"
	MethodFsReadDirectory                        = "fs/readDirectory"
	MethodFsReadFile                             = "fs/readFile"
	MethodFsRemove                               = "fs/remove"
	MethodFsUnwatch                              = "fs/unwatch"
	MethodFsWatch                                = "fs/watch"
	MethodFsWriteFile                            = "fs/writeFile"
	MethodFuzzyFileSearch                        = "fuzzyFileSearch"
	// MethodFuzzyFileSearchSessionStart is experimental; see WithExperimentalAPI.
	MethodFuzzyFileSearchSessionStart = "fuzzyFileSearch/sessionStart"
	// MethodFuzzyFileSearchSessionStop is experimental; see WithExperimentalAPI.
	MethodFuzzyFileSearchSessionStop = "fuzzyFileSearch/sessionStop"
	// MethodFuzzyFileSearchSessionUpdate is experimental; see WithExperimentalAPI.
	MethodFuzzyFileSearchSessionUpdate = "fuzzyFileSearch/sessionUpdate"
	MethodHooksList                    = "hooks/list"
	MethodInitialize                   = "initialize"
	MethodMarketplaceAdd               = "marketplace/add"
	MethodMarketplaceRemove            = "marketplace/remove"
	MethodMarketplaceUpgrade           = "marketplace/upgrade"
	MethodMcpServerOAuthLogin          = "mcpServer/oauth/login"
	MethodMcpServerResourceRead        = "mcpServer/resource/read"
	MethodMcpServerToolCall            = "mcpServer/tool/call"
	MethodMcpServerStatusList          = "mcpServerStatus/list"
	// MethodMemoryReset is experimental; see WithExperimentalAPI.
	MethodMemoryReset = "memory/reset"
	// MethodMockExperimentalMethod is experimental; see WithExperimentalAPI.
	MethodMockExperimentalMethod        = "mock/experimentalMethod"
	MethodModelList                     = "model/list"
	MethodModelProviderCapabilitiesRead = "modelProvider/capabilities/read"
	MethodPermissionProfileList         = "permissionProfile/list"
	MethodPluginInstall                 = "plugin/install"
	MethodPluginInstalled               = "plugin/installed"
	MethodPluginList                    = "plugin/list"
	MethodPluginRead                    = "plugin/read"
	// MethodPluginSearch is experimental; see WithExperimentalAPI.
	MethodPluginSearch             = "plugin/search"
	MethodPluginShareCheckout      = "plugin/share/checkout"
	MethodPluginShareDelete        = "plugin/share/delete"
	MethodPluginShareList          = "plugin/share/list"
	MethodPluginShareSave          = "plugin/share/save"
	MethodPluginShareUpdateTargets = "plugin/share/updateTargets"
	MethodPluginSkillRead          = "plugin/skill/read"
	MethodPluginUninstall          = "plugin/uninstall"
	// MethodProcessKill is experimental; see WithExperimentalAPI.
	MethodProcessKill = "process/kill"
	// MethodProcessResizePty is experimental; see WithExperimentalAPI.
	MethodProcessResizePty = "process/resizePty"
	// MethodProcessSpawn is experimental; see WithExperimentalAPI.
	MethodProcessSpawn = "process/spawn"
	// MethodProcessWriteStdin is experimental; see WithExperimentalAPI.
	MethodProcessWriteStdin = "process/writeStdin"
	// MethodProjectCreate is experimental; see WithExperimentalAPI.
	MethodProjectCreate = "project/create"
	// MethodProjectDelete is experimental; see WithExperimentalAPI.
	MethodProjectDelete = "project/delete"
	// MethodProjectImport is experimental; see WithExperimentalAPI.
	MethodProjectImport = "project/import"
	// MethodProjectList is experimental; see WithExperimentalAPI.
	MethodProjectList = "project/list"
	// MethodProjectMove is experimental; see WithExperimentalAPI.
	MethodProjectMove = "project/move"
	// MethodProjectRead is experimental; see WithExperimentalAPI.
	MethodProjectRead = "project/read"
	// MethodProjectUpdate is experimental; see WithExperimentalAPI.
	MethodProjectUpdate = "project/update"
	// MethodRemoteControlClientList is experimental; see WithExperimentalAPI.
	MethodRemoteControlClientList = "remoteControl/client/list"
	// MethodRemoteControlClientRevoke is experimental; see WithExperimentalAPI.
	MethodRemoteControlClientRevoke = "remoteControl/client/revoke"
	// MethodRemoteControlDisable is experimental; see WithExperimentalAPI.
	MethodRemoteControlDisable = "remoteControl/disable"
	// MethodRemoteControlEnable is experimental; see WithExperimentalAPI.
	MethodRemoteControlEnable = "remoteControl/enable"
	// MethodRemoteControlPairingStart is experimental; see WithExperimentalAPI.
	MethodRemoteControlPairingStart = "remoteControl/pairing/start"
	// MethodRemoteControlPairingStatus is experimental; see WithExperimentalAPI.
	MethodRemoteControlPairingStatus = "remoteControl/pairing/status"
	// MethodRemoteControlStatusRead is experimental; see WithExperimentalAPI.
	MethodRemoteControlStatusRead = "remoteControl/status/read"
	MethodReviewStart             = "review/start"
	// MethodServerDiagnostics is experimental; see WithExperimentalAPI.
	MethodServerDiagnostics                 = "server/diagnostics"
	MethodSkillsConfigWrite                 = "skills/config/write"
	MethodSkillsExtraRootsSet               = "skills/extraRoots/set"
	MethodSkillsList                        = "skills/list"
	MethodThreadApproveGuardianDeniedAction = "thread/approveGuardianDeniedAction"
	MethodThreadArchive                     = "thread/archive"
	// MethodThreadBackgroundTerminalsClean is experimental; see WithExperimentalAPI.
	MethodThreadBackgroundTerminalsClean = "thread/backgroundTerminals/clean"
	// MethodThreadBackgroundTerminalsList is experimental; see WithExperimentalAPI.
	MethodThreadBackgroundTerminalsList = "thread/backgroundTerminals/list"
	// MethodThreadBackgroundTerminalsTerminate is experimental; see WithExperimentalAPI.
	MethodThreadBackgroundTerminalsTerminate = "thread/backgroundTerminals/terminate"
	MethodThreadCompactStart                 = "thread/compact/start"
	// MethodThreadDecrementElicitation is experimental; see WithExperimentalAPI.
	MethodThreadDecrementElicitation = "thread/decrement_elicitation"
	MethodThreadDelete               = "thread/delete"
	MethodThreadFork                 = "thread/fork"
	MethodThreadGoalClear            = "thread/goal/clear"
	MethodThreadGoalGet              = "thread/goal/get"
	MethodThreadGoalSet              = "thread/goal/set"
	// MethodThreadIncrementElicitation is experimental; see WithExperimentalAPI.
	MethodThreadIncrementElicitation = "thread/increment_elicitation"
	MethodThreadInjectItems          = "thread/inject_items"
	// MethodThreadItemsList is experimental; see WithExperimentalAPI.
	MethodThreadItemsList  = "thread/items/list"
	MethodThreadList       = "thread/list"
	MethodThreadLoadedList = "thread/loaded/list"
	// MethodThreadMemoryModeSet is experimental; see WithExperimentalAPI.
	MethodThreadMemoryModeSet  = "thread/memoryMode/set"
	MethodThreadMetadataUpdate = "thread/metadata/update"
	MethodThreadNameSet        = "thread/name/set"
	// MethodThreadQueueAdd is experimental; see WithExperimentalAPI.
	MethodThreadQueueAdd = "thread/queue/add"
	// MethodThreadQueueDelete is experimental; see WithExperimentalAPI.
	MethodThreadQueueDelete = "thread/queue/delete"
	// MethodThreadQueueList is experimental; see WithExperimentalAPI.
	MethodThreadQueueList = "thread/queue/list"
	// MethodThreadQueueReorder is experimental; see WithExperimentalAPI.
	MethodThreadQueueReorder = "thread/queue/reorder"
	// MethodThreadQueueStart is experimental; see WithExperimentalAPI.
	MethodThreadQueueStart = "thread/queue/start"
	// MethodThreadQueueUpdate is experimental; see WithExperimentalAPI.
	MethodThreadQueueUpdate = "thread/queue/update"
	MethodThreadRead        = "thread/read"
	// MethodThreadRealtimeAppendAudio is experimental; see WithExperimentalAPI.
	MethodThreadRealtimeAppendAudio = "thread/realtime/appendAudio"
	// MethodThreadRealtimeAppendSpeech is experimental; see WithExperimentalAPI.
	MethodThreadRealtimeAppendSpeech = "thread/realtime/appendSpeech"
	// MethodThreadRealtimeAppendText is experimental; see WithExperimentalAPI.
	MethodThreadRealtimeAppendText = "thread/realtime/appendText"
	// MethodThreadRealtimeListVoices is experimental; see WithExperimentalAPI.
	MethodThreadRealtimeListVoices = "thread/realtime/listVoices"
	// MethodThreadRealtimeStart is experimental; see WithExperimentalAPI.
	MethodThreadRealtimeStart = "thread/realtime/start"
	// MethodThreadRealtimeStop is experimental; see WithExperimentalAPI.
	MethodThreadRealtimeStop = "thread/realtime/stop"
	MethodThreadResume       = "thread/resume"
	// MethodThreadRevert is experimental; see WithExperimentalAPI.
	MethodThreadRevert   = "thread/revert"
	MethodThreadRollback = "thread/rollback"
	// MethodThreadSearch is experimental; see WithExperimentalAPI.
	MethodThreadSearch = "thread/search"
	// MethodThreadSearchOccurrences is experimental; see WithExperimentalAPI.
	MethodThreadSearchOccurrences = "thread/searchOccurrences"
	MethodThreadSectionMove       = "thread/section/move"
	// MethodThreadSettingsUpdate is experimental; see WithExperimentalAPI.
	MethodThreadSettingsUpdate = "thread/settings/update"
	MethodThreadShellCommand   = "thread/shellCommand"
	MethodThreadStart          = "thread/start"
	// MethodThreadTurnsList is experimental; see WithExperimentalAPI.
	MethodThreadTurnsList          = "thread/turns/list"
	MethodThreadUnarchive          = "thread/unarchive"
	MethodThreadUnsubscribe        = "thread/unsubscribe"
	MethodThreadSectionCreate      = "threadSection/create"
	MethodThreadSectionDelete      = "threadSection/delete"
	MethodThreadSectionList        = "threadSection/list"
	MethodThreadSectionUpdate      = "threadSection/update"
	MethodTurnInterrupt            = "turn/interrupt"
	MethodTurnStart                = "turn/start"
	MethodTurnSteer                = "turn/steer"
	MethodWindowsSandboxReadiness  = "windowsSandbox/readiness"
	MethodWindowsSandboxSetupStart = "windowsSandbox/setupStart"
)

// Methods the server sends to the client. Each MUST be answered: an
// unanswered server request blocks the turn indefinitely.
const (
	ServerMethodAccountChatgptAuthTokensRefresh = "account/chatgptAuthTokens/refresh"
	ServerMethodApplyPatchApproval              = "applyPatchApproval"
	ServerMethodAttestationGenerate             = "attestation/generate"
	// ServerMethodCurrentTimeRead is experimental; see WithExperimentalAPI.
	ServerMethodCurrentTimeRead                     = "currentTime/read"
	ServerMethodExecCommandApproval                 = "execCommandApproval"
	ServerMethodItemCommandExecutionRequestApproval = "item/commandExecution/requestApproval"
	ServerMethodItemFileChangeRequestApproval       = "item/fileChange/requestApproval"
	ServerMethodItemPermissionsRequestApproval      = "item/permissions/requestApproval"
	ServerMethodItemToolCall                        = "item/tool/call"
	ServerMethodItemToolRequestUserInput            = "item/tool/requestUserInput"
	ServerMethodMcpServerElicitationRequest         = "mcpServer/elicitation/request"
)

// One-way notifications the server sends to the client.
const (
	NotifyAccountLoginCompleted                   = "account/login/completed"
	NotifyAccountRateLimitsUpdated                = "account/rateLimits/updated"
	NotifyAccountUpdated                          = "account/updated"
	NotifyAppListUpdated                          = "app/list/updated"
	NotifyAutoApprovalReviewStrictReviewRequired  = "autoApprovalReview/strictReviewRequired"
	NotifyCommandExecOutputDelta                  = "command/exec/outputDelta"
	NotifyConfigWarning                           = "configWarning"
	NotifyDeprecationNotice                       = "deprecationNotice"
	NotifyError                                   = "error"
	NotifyExternalAgentConfigImportCompleted      = "externalAgentConfig/import/completed"
	NotifyExternalAgentConfigImportProgress       = "externalAgentConfig/import/progress"
	NotifyFsChanged                               = "fs/changed"
	NotifyFuzzyFileSearchSessionCompleted         = "fuzzyFileSearch/sessionCompleted"
	NotifyFuzzyFileSearchSessionUpdated           = "fuzzyFileSearch/sessionUpdated"
	NotifyGuardianWarning                         = "guardianWarning"
	NotifyHookCompleted                           = "hook/completed"
	NotifyHookStarted                             = "hook/started"
	NotifyItemAgentMessageDelta                   = "item/agentMessage/delta"
	NotifyItemAutoApprovalReviewCompleted         = "item/autoApprovalReview/completed"
	NotifyItemAutoApprovalReviewStarted           = "item/autoApprovalReview/started"
	NotifyItemCommandExecutionOutputDelta         = "item/commandExecution/outputDelta"
	NotifyItemCommandExecutionTerminalInteraction = "item/commandExecution/terminalInteraction"
	NotifyItemCompleted                           = "item/completed"
	NotifyItemFileChangeOutputDelta               = "item/fileChange/outputDelta"
	NotifyItemFileChangePatchUpdated              = "item/fileChange/patchUpdated"
	NotifyItemMcpToolCallProgress                 = "item/mcpToolCall/progress"
	NotifyItemPlanDelta                           = "item/plan/delta"
	NotifyItemReasoningSummaryPartAdded           = "item/reasoning/summaryPartAdded"
	NotifyItemReasoningSummaryTextDelta           = "item/reasoning/summaryTextDelta"
	NotifyItemReasoningTextDelta                  = "item/reasoning/textDelta"
	NotifyItemStarted                             = "item/started"
	NotifyMcpServerOauthLoginCompleted            = "mcpServer/oauthLogin/completed"
	NotifyMcpServerStartupStatusUpdated           = "mcpServer/startupStatus/updated"
	NotifyModelRerouted                           = "model/rerouted"
	NotifyModelSafetyBufferingUpdated             = "model/safetyBuffering/updated"
	NotifyModelVerification                       = "model/verification"
	NotifyProcessExited                           = "process/exited"
	NotifyProcessOutputDelta                      = "process/outputDelta"
	NotifyProjectChanged                          = "project/changed"
	NotifyRemoteControlStatusChanged              = "remoteControl/status/changed"
	NotifyServerRequestResolved                   = "serverRequest/resolved"
	NotifySkillsChanged                           = "skills/changed"
	NotifyThreadArchived                          = "thread/archived"
	NotifyThreadClosed                            = "thread/closed"
	NotifyThreadCompacted                         = "thread/compacted"
	NotifyThreadDeleted                           = "thread/deleted"
	NotifyThreadEnvironmentConnected              = "thread/environment/connected"
	NotifyThreadEnvironmentDisconnected           = "thread/environment/disconnected"
	NotifyThreadGoalCleared                       = "thread/goal/cleared"
	NotifyThreadGoalUpdated                       = "thread/goal/updated"
	NotifyThreadNameUpdated                       = "thread/name/updated"
	NotifyThreadProjectUpdated                    = "thread/project/updated"
	NotifyThreadQueueChanged                      = "thread/queue/changed"
	NotifyThreadRealtimeClosed                    = "thread/realtime/closed"
	NotifyThreadRealtimeError                     = "thread/realtime/error"
	NotifyThreadRealtimeItemAdded                 = "thread/realtime/itemAdded"
	NotifyThreadRealtimeOutputAudioDelta          = "thread/realtime/outputAudio/delta"
	NotifyThreadRealtimeSDP                       = "thread/realtime/sdp"
	NotifyThreadRealtimeStarted                   = "thread/realtime/started"
	NotifyThreadRealtimeTranscriptDelta           = "thread/realtime/transcript/delta"
	NotifyThreadRealtimeTranscriptDone            = "thread/realtime/transcript/done"
	NotifyThreadReverted                          = "thread/reverted"
	NotifyThreadSettingsUpdated                   = "thread/settings/updated"
	NotifyThreadStarted                           = "thread/started"
	NotifyThreadStatusChanged                     = "thread/status/changed"
	NotifyThreadTokenUsageUpdated                 = "thread/tokenUsage/updated"
	NotifyThreadUnarchived                        = "thread/unarchived"
	NotifyTurnCompleted                           = "turn/completed"
	NotifyTurnDiffUpdated                         = "turn/diff/updated"
	NotifyTurnModerationMetadata                  = "turn/moderationMetadata"
	NotifyTurnPlanUpdated                         = "turn/plan/updated"
	NotifyTurnStarted                             = "turn/started"
	NotifyWarning                                 = "warning"
	NotifyWindowsWorldWritableWarning             = "windows/worldWritableWarning"
	NotifyWindowsSandboxSetupCompleted            = "windowsSandbox/setupCompleted"
)

// NotificationParams returns a zero value of the params type for a server
// notification method, or nil if this build does not know the method.
// A nil return is not an error: it means the server is newer than this SDK,
// and the caller should surface the raw payload instead.
func NotificationParams(method string) any {
	switch method {
	case "account/login/completed":
		return new(AccountLoginCompletedNotification)
	case "account/rateLimits/updated":
		return new(AccountRateLimitsUpdatedNotification)
	case "account/updated":
		return new(AccountUpdatedNotification)
	case "app/list/updated":
		return new(AppListUpdatedNotification)
	case "autoApprovalReview/strictReviewRequired":
		return new(StrictReviewRequiredNotification)
	case "command/exec/outputDelta":
		return new(CommandExecOutputDeltaNotification)
	case "configWarning":
		return new(ConfigWarningNotification)
	case "deprecationNotice":
		return new(DeprecationNoticeNotification)
	case "error":
		return new(ErrorNotification)
	case "externalAgentConfig/import/completed":
		return new(ExternalAgentConfigImportCompletedNotification)
	case "externalAgentConfig/import/progress":
		return new(ExternalAgentConfigImportProgressNotification)
	case "fs/changed":
		return new(FsChangedNotification)
	case "fuzzyFileSearch/sessionCompleted":
		return new(FuzzyFileSearchSessionCompletedNotification)
	case "fuzzyFileSearch/sessionUpdated":
		return new(FuzzyFileSearchSessionUpdatedNotification)
	case "guardianWarning":
		return new(GuardianWarningNotification)
	case "hook/completed":
		return new(HookCompletedNotification)
	case "hook/started":
		return new(HookStartedNotification)
	case "item/agentMessage/delta":
		return new(AgentMessageDeltaNotification)
	case "item/autoApprovalReview/completed":
		return new(ItemGuardianApprovalReviewCompletedNotification)
	case "item/autoApprovalReview/started":
		return new(ItemGuardianApprovalReviewStartedNotification)
	case "item/commandExecution/outputDelta":
		return new(CommandExecutionOutputDeltaNotification)
	case "item/commandExecution/terminalInteraction":
		return new(TerminalInteractionNotification)
	case "item/completed":
		return new(ItemCompletedNotification)
	case "item/fileChange/outputDelta":
		return new(FileChangeOutputDeltaNotification)
	case "item/fileChange/patchUpdated":
		return new(FileChangePatchUpdatedNotification)
	case "item/mcpToolCall/progress":
		return new(MCPToolCallProgressNotification)
	case "item/plan/delta":
		return new(PlanDeltaNotification)
	case "item/reasoning/summaryPartAdded":
		return new(ReasoningSummaryPartAddedNotification)
	case "item/reasoning/summaryTextDelta":
		return new(ReasoningSummaryTextDeltaNotification)
	case "item/reasoning/textDelta":
		return new(ReasoningTextDeltaNotification)
	case "item/started":
		return new(ItemStartedNotification)
	case "mcpServer/oauthLogin/completed":
		return new(MCPServerOAuthLoginCompletedNotification)
	case "mcpServer/startupStatus/updated":
		return new(MCPServerStatusUpdatedNotification)
	case "model/rerouted":
		return new(ModelReroutedNotification)
	case "model/safetyBuffering/updated":
		return new(ModelSafetyBufferingUpdatedNotification)
	case "model/verification":
		return new(ModelVerificationNotification)
	case "process/exited":
		return new(ProcessExitedNotification)
	case "process/outputDelta":
		return new(ProcessOutputDeltaNotification)
	case "project/changed":
		return new(ProjectChangedNotification)
	case "remoteControl/status/changed":
		return new(RemoteControlStatusChangedNotification)
	case "serverRequest/resolved":
		return new(ServerRequestResolvedNotification)
	case "skills/changed":
		return new(SkillsChangedNotification)
	case "thread/archived":
		return new(ThreadArchivedNotification)
	case "thread/closed":
		return new(ThreadClosedNotification)
	case "thread/compacted":
		return new(ContextCompactedNotification)
	case "thread/deleted":
		return new(ThreadDeletedNotification)
	case "thread/environment/connected":
		return new(EnvironmentConnectionNotification)
	case "thread/environment/disconnected":
		return new(EnvironmentConnectionNotification)
	case "thread/goal/cleared":
		return new(ThreadGoalClearedNotification)
	case "thread/goal/updated":
		return new(ThreadGoalUpdatedNotification)
	case "thread/name/updated":
		return new(ThreadNameUpdatedNotification)
	case "thread/project/updated":
		return new(ThreadProjectUpdatedNotification)
	case "thread/queue/changed":
		return new(ThreadQueueChangedNotification)
	case "thread/realtime/closed":
		return new(ThreadRealtimeClosedNotification)
	case "thread/realtime/error":
		return new(ThreadRealtimeErrorNotification)
	case "thread/realtime/itemAdded":
		return new(ThreadRealtimeItemAddedNotification)
	case "thread/realtime/outputAudio/delta":
		return new(ThreadRealtimeOutputAudioDeltaNotification)
	case "thread/realtime/sdp":
		return new(ThreadRealtimeSDPNotification)
	case "thread/realtime/started":
		return new(ThreadRealtimeStartedNotification)
	case "thread/realtime/transcript/delta":
		return new(ThreadRealtimeTranscriptDeltaNotification)
	case "thread/realtime/transcript/done":
		return new(ThreadRealtimeTranscriptDoneNotification)
	case "thread/reverted":
		return new(ThreadRevertedNotification)
	case "thread/settings/updated":
		return new(ThreadSettingsUpdatedNotification)
	case "thread/started":
		return new(ThreadStartedNotification)
	case "thread/status/changed":
		return new(ThreadStatusChangedNotification)
	case "thread/tokenUsage/updated":
		return new(ThreadTokenUsageUpdatedNotification)
	case "thread/unarchived":
		return new(ThreadUnarchivedNotification)
	case "turn/completed":
		return new(TurnCompletedNotification)
	case "turn/diff/updated":
		return new(TurnDiffUpdatedNotification)
	case "turn/moderationMetadata":
		return new(TurnModerationMetadataNotification)
	case "turn/plan/updated":
		return new(TurnPlanUpdatedNotification)
	case "turn/started":
		return new(TurnStartedNotification)
	case "warning":
		return new(WarningNotification)
	case "windows/worldWritableWarning":
		return new(WindowsWorldWritableWarningNotification)
	case "windowsSandbox/setupCompleted":
		return new(WindowsSandboxSetupCompletedNotification)
	}
	return nil
}

// ServerRequestParams returns a zero value of the params type for a
// server-initiated request method, or nil if unknown to this build.
func ServerRequestParams(method string) any {
	switch method {
	case "account/chatgptAuthTokens/refresh":
		return new(ChatgptAuthTokensRefreshParams)
	case "applyPatchApproval":
		return new(ApplyPatchApprovalParams)
	case "attestation/generate":
		return new(AttestationGenerateParams)
	case "currentTime/read":
		return new(CurrentTimeReadParams)
	case "execCommandApproval":
		return new(ExecCommandApprovalParams)
	case "item/commandExecution/requestApproval":
		return new(CommandExecutionRequestApprovalParams)
	case "item/fileChange/requestApproval":
		return new(FileChangeRequestApprovalParams)
	case "item/permissions/requestApproval":
		return new(PermissionsRequestApprovalParams)
	case "item/tool/call":
		return new(DynamicToolCallParams)
	case "item/tool/requestUserInput":
		return new(ToolRequestUserInputParams)
	case "mcpServer/elicitation/request":
		return new(MCPServerElicitationRequestParams)
	}
	return nil
}
