package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type generator struct {
	defs    map[string]Def
	methods *MethodTable
	version string
	exp     *Experimental
}

const genHeader = `// Code generated by internal/cmd/schemagen. DO NOT EDIT.
//
// Source: internal/schemas, generated from codex-cli %s.
// Regenerate with ` + "`make generate`" + `.

package protocol

`

func (g *generator) emitAll(dir string, names []string) error {
	files := map[string]func(*bytes.Buffer, []string) error{
		"types_gen.go":   g.emitTypes,
		"enums_gen.go":   g.emitEnums,
		"unions_gen.go":  g.emitUnions,
		"methods_gen.go": g.emitMethods,
	}
	for name, fn := range files {
		var buf bytes.Buffer
		fmt.Fprintf(&buf, genHeader, g.version)
		if err := fn(&buf, names); err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		src, err := format.Source(buf.Bytes())
		if err != nil {
			// Write the unformatted output so the syntax error is inspectable.
			_ = os.WriteFile(filepath.Join(dir, name+".broken"), buf.Bytes(), 0o644)
			return fmt.Errorf("%s: generated code does not parse (wrote %s.broken): %w", name, name, err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), src, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// emitTypes writes plain structs and scalar aliases.
func (g *generator) emitTypes(b *bytes.Buffer, names []string) error {
	b.WriteString("import \"encoding/json\"\n\n")
	b.WriteString("// SchemaVersion is the codex-cli version these types were generated from.\n")
	b.WriteString("// It is recorded for diagnostics and never enforced against the running\n")
	b.WriteString("// server: a newer server may send methods, fields, and enum values this\n")
	b.WriteString("// build does not know, and all of them decode without error.\n")
	fmt.Fprintf(b, "const SchemaVersion = %q\n\n", g.version)

	for _, name := range names {
		d := g.defs[name]
		switch d.Kind {
		case KindAliasString:
			writeDoc(b, d.Schema.Description)
			if g.exp.IsDef(name) {
				writeDoc(b, experimentalDoc)
			}
			fmt.Fprintf(b, "type %s string\n\n", goIdent(name))
		case KindAliasNumber:
			writeDoc(b, d.Schema.Description)
			if g.exp.IsDef(name) {
				writeDoc(b, experimentalDoc)
			}
			fmt.Fprintf(b, "type %s %s\n\n", goIdent(name),
				numericGoType(d.Schema.Format, d.Schema.hasType("integer")))
		case KindStruct:
			g.emitStruct(b, goIdent(name), name, d)
		}
	}
	return nil
}

// emitStruct writes one struct. goName must already be a valid Go identifier:
// goIdent is not idempotent (it would re-split "HTTPConnectionFailed" into
// "Httpconnection Failed"), so callers convert once and pass the result.
func (g *generator) emitStruct(b *bytes.Buffer, goName, schemaName string, d Def) {
	writeDoc(b, d.Schema.Description)
	if g.exp.IsDef(schemaName) {
		writeDoc(b, experimentalDoc)
	}
	fields := g.fieldsOf(schemaName, d.Schema)
	if len(fields) == 0 {
		// 29 definitions are empty objects: the responses of methods that answer
		// with {}. A named empty struct keeps the method signatures uniform.
		fmt.Fprintf(b, "type %s struct{}\n\n", goName)
		return
	}
	fmt.Fprintf(b, "type %s struct {\n", goName)
	for _, f := range fields {
		if f.Doc != "" {
			for _, line := range strings.Split(f.Doc, "\n") {
				fmt.Fprintf(b, "\t// %s\n", line)
			}
		}
		if f.Experimental {
			for _, line := range strings.Split(experimentalDoc, "\n") {
				fmt.Fprintf(b, "\t// %s\n", line)
			}
		}
		if f.TriState {
			b.WriteString("\t// Tri-state: absent leaves the value unchanged, an explicit null clears it.\n")
		}
		fmt.Fprintf(b, "\t%s %s %s\n", f.GoName, f.GoType, f.tag())
	}
	b.WriteString("}\n\n")

	// Emit the inline payload structs this type referenced.
	for _, f := range g.inlineStructsOf(schemaName, d.Schema) {
		g.emitStruct(b, f.name, f.name, Def{Name: f.name, Schema: f.schema, Kind: KindStruct})
	}
}

type inlineStruct struct {
	name   string
	schema *Schema
}

func (g *generator) inlineStructsOf(owner string, s *Schema) []inlineStruct {
	var out []inlineStruct
	keys := sortedKeys(s.Properties)
	for _, k := range keys {
		p := s.Properties[k]
		if p.hasType("object") && len(p.Properties) > 0 {
			out = append(out, inlineStruct{name: g.inlineStructName(owner, k), schema: p})
		}
	}
	return out
}

func (g *generator) fieldsOf(owner string, s *Schema) []fieldSpec {
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	var out []fieldSpec
	for _, wire := range sortedKeys(s.Properties) {
		p := s.Properties[wire]
		goType, needsPtr := g.goType(p, owner, wire)
		f := fieldSpec{
			GoName:       goIdent(wire),
			WireName:     wire,
			Doc:          strings.TrimSpace(p.Description),
			Required:     required[wire],
			Nullable:     p.nullable(),
			TriState:     triStateFields[owner+"."+wire],
			Experimental: g.exp.IsField(owner, wire),
		}
		switch {
		case f.TriState:
			f.GoType = "*Nullable[" + goType + "]"
		case needsPtr || (!f.Required && !strings.HasPrefix(goType, "[]") &&
			!strings.HasPrefix(goType, "map[") && goType != "json.RawMessage"):
			f.GoType = "*" + goType
		default:
			f.GoType = goType
		}
		out = append(out, f)
	}
	// A field named like its own type reads badly; nothing to do about it here,
	// but keep deterministic order for stable output.
	sort.SliceStable(out, func(i, j int) bool { return out[i].WireName < out[j].WireName })
	return out
}

// emitEnums writes string-typed enums. The Go identifier is derived from the
// wire value, but the constant's VALUE is always copied verbatim, because the
// schema mixes four casing conventions.
func (g *generator) emitEnums(b *bytes.Buffer, names []string) error {
	for _, name := range names {
		d := g.defs[name]
		if d.Kind != KindEnum {
			continue
		}
		goName := goIdent(name)
		writeDoc(b, d.Schema.Description)
		if g.exp.IsDef(name) {
			writeDoc(b, experimentalDoc)
		}
		fmt.Fprintf(b, "type %s string\n\n", goName)

		values := make([]string, 0, len(d.Schema.Enum))
		for _, raw := range d.Schema.Enum {
			if s, ok := raw.(string); ok {
				values = append(values, s)
			}
		}
		fmt.Fprintf(b, "const (\n")
		for _, v := range values {
			fmt.Fprintf(b, "\t%s %s = %q\n", enumConstName(goName, v), goName, v)
		}
		fmt.Fprintf(b, ")\n\n")

		// IsKnown lets a caller detect a value from a newer server without the
		// SDK rejecting it. Unknown values decode and re-encode unchanged.
		fmt.Fprintf(b, "// IsKnown reports whether v is a value this build recognizes. A newer\n")
		fmt.Fprintf(b, "// server may send values that are not, and those are preserved as-is.\n")
		fmt.Fprintf(b, "func (v %s) IsKnown() bool {\n\tswitch v {\n\tcase ", goName)
		consts := make([]string, len(values))
		for i, v := range values {
			consts[i] = enumConstName(goName, v)
		}
		fmt.Fprintf(b, "%s:\n\t\treturn true\n\t}\n\treturn false\n}\n\n", strings.Join(consts, ",\n\t\t"))
		fmt.Fprintf(b, "// String returns the wire value.\n")
		fmt.Fprintf(b, "func (v %s) String() string { return string(v) }\n\n", goName)
	}
	return nil
}

// emitMethods writes the method-name constants and the method-to-type tables.
func (g *generator) emitMethods(b *bytes.Buffer, _ []string) error {
	sections := []struct {
		title   string
		prefix  string
		entries []MethodEntry
		comment string
	}{
		{"client requests", "Method", g.methods.ClientRequests,
			"Methods the client sends to the server, each expecting a result."},
		{"server requests", "ServerMethod", g.methods.ServerRequests,
			"Methods the server sends to the client. Each MUST be answered: an\n" +
				"unanswered server request blocks the turn indefinitely."},
		{"server notifications", "Notify", g.methods.ServerNotifications,
			"One-way notifications the server sends to the client."},
	}
	for _, sec := range sections {
		for _, line := range strings.Split(sec.comment, "\n") {
			fmt.Fprintf(b, "// %s\n", line)
		}
		b.WriteString("const (\n")
		for _, e := range sec.entries {
			if g.exp.IsMethod(e.Method) {
				fmt.Fprintf(b, "\t// %s%s is experimental; see WithExperimentalAPI.\n", sec.prefix, e.GoName)
			}
			fmt.Fprintf(b, "\t%s%s = %q\n", sec.prefix, e.GoName, e.Method)
		}
		b.WriteString(")\n\n")
	}

	// A method -> zero-value params/result factory table, so the dispatcher can
	// decode a payload without a hand-written switch over 75 notifications.
	b.WriteString("// NotificationParams returns a zero value of the params type for a server\n")
	b.WriteString("// notification method, or nil if this build does not know the method.\n")
	b.WriteString("// A nil return is not an error: it means the server is newer than this SDK,\n")
	b.WriteString("// and the caller should surface the raw payload instead.\n")
	b.WriteString("func NotificationParams(method string) any {\n\tswitch method {\n")
	for _, e := range g.methods.ServerNotifications {
		if e.Params == "" {
			continue
		}
		if d, ok := g.defs[e.Params]; !ok || d.Kind == KindRaw {
			continue
		}
		fmt.Fprintf(b, "\tcase %q:\n\t\treturn new(%s)\n", e.Method, goIdent(e.Params))
	}
	b.WriteString("\t}\n\treturn nil\n}\n\n")

	b.WriteString("// ServerRequestParams returns a zero value of the params type for a\n")
	b.WriteString("// server-initiated request method, or nil if unknown to this build.\n")
	b.WriteString("func ServerRequestParams(method string) any {\n\tswitch method {\n")
	for _, e := range g.methods.ServerRequests {
		if e.Params == "" {
			continue
		}
		if d, ok := g.defs[e.Params]; !ok || d.Kind == KindRaw {
			continue
		}
		fmt.Fprintf(b, "\tcase %q:\n\t\treturn new(%s)\n", e.Method, goIdent(e.Params))
	}
	b.WriteString("\t}\n\treturn nil\n}\n\n")
	return nil
}

func writeDoc(b *bytes.Buffer, doc string) {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return
	}
	for _, line := range strings.Split(doc, "\n") {
		fmt.Fprintf(b, "// %s\n", strings.TrimSpace(line))
	}
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// jsonUnmarshalLenient decodes a value that may legitimately be the boolean
// `true` rather than a schema object (additionalProperties allows both).
func jsonUnmarshalLenient(raw json.RawMessage, dst *Schema) error {
	var b bool
	if err := json.Unmarshal(raw, &b); err == nil {
		return fmt.Errorf("boolean additionalProperties")
	}
	return json.Unmarshal(raw, dst)
}
